### ISSUE TITLE
Dokka fails after updating to 1.1-M03

### ISSUE THREAD

**Issue by nhaarman** [Kotlin/dokka#120]
After updating a project's Kotlin version from 1.1-M02 to 1.1-M03, Dokka fails with the following stacktrace:

```
▶ gw dokka -s
Parallel execution is an incubating feature.
Incremental java compilation is an incubating feature.
:myproject:dokka FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':myproject:dokka'.
> Could not initialize class dokkaorg.jetbrains.kotlin.platform.JavaToKotlinClassMap

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':myproject:dokka'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:66)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class dokkaorg.jetbrains.kotlin.platform.JavaToKotlinClassMap
        at dokkaorg.jetbrains.kotlin.resolve.jvm.platform.JvmPlatform$defaultModuleParameters$1.getPlatformToKotlinClassMap(JvmPlatform.kt:35)
        at dokkaorg.jetbrains.kotlin.descriptors.impl.ModuleDescriptorImpl.getPlatformToKotlinClassMap(ModuleDescriptorImpl.kt)
        at dokkaorg.jetbrains.kotlin.context.ModuleContext$DefaultImpls.getPlatformToKotlinClassMap(context.kt:46)
        at dokkaorg.jetbrains.kotlin.context.ModuleContextImpl.getPlatformToKotlinClassMap(context.kt:85)
        at dokkaorg.jetbrains.kotlin.frontend.di.InjectionKt.configureModule(injection.kt:40)
        at dokkaorg.jetbrains.kotlin.frontend.di.InjectionKt.configureModule(injection.kt:60)
        at dokkaorg.jetbrains.kotlin.frontend.java.di.InjectionKt$createContainerForLazyResolveWithJava$1.invoke(injection.kt:91)
        at dokkaorg.jetbrains.kotlin.frontend.java.di.InjectionKt$createContainerForLazyResolveWithJava$1.invoke(injection.kt)
        at dokkaorg.jetbrains.kotlin.container.DslKt.createContainer(Dsl.kt:23)
        at dokkaorg.jetbrains.kotlin.frontend.java.di.InjectionKt.createContainerForLazyResolveWithJava(injection.kt:87)
        at dokkaorg.jetbrains.kotlin.resolve.jvm.JvmAnalyzerFacade.createResolverForModule(JvmAnalyzerFacade.kt:86)
        at dokkaorg.jetbrains.kotlin.resolve.jvm.JvmAnalyzerFacade.createResolverForModule(JvmAnalyzerFacade.kt:48)
        at dokkaorg.jetbrains.kotlin.analyzer.AnalyzerFacade$setupResolverForProject$6$initializeResolverForProject$$inlined$forEach$lambda$1.invoke(AnalyzerFacade.kt:210)
        at dokkaorg.jetbrains.kotlin.analyzer.AnalyzerFacade$setupResolverForProject$6$initializeResolverForProject$$inlined$forEach$lambda$1.invoke(AnalyzerFacade.kt:147)
        at dokkaorg.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedLazyValue.invoke(LockBasedStorageManager.java:321)
        at dokkaorg.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedNotNullLazyValue.invoke(LockBasedStorageManager.java:362)
        at dokkaorg.jetbrains.kotlin.analyzer.ResolverForProjectImpl.resolverForModuleDescriptor(AnalyzerFacade.kt:90)
        at dokkaorg.jetbrains.kotlin.analyzer.ResolverForProject.resolverForModule(AnalyzerFacade.kt:44)
        at org.jetbrains.dokka.AnalysisEnvironment.createResolutionFacade(AnalysisEnvironment.kt:100)
        at org.jetbrains.dokka.Utilities.DokkaModule.configure(DokkaModule.kt:53)
        at dokkacom.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
        at dokkacom.google.inject.spi.Elements.getElements(Elements.java:110)
        at dokkacom.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
        at dokkacom.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
        at dokkacom.google.inject.Guice.createInjector(Guice.java:99)
        at dokkacom.google.inject.Guice.createInjector(Guice.java:73)
        at dokkacom.google.inject.Guice.createInjector(Guice.java:62)
        at org.jetbrains.dokka.DokkaGenerator.generate(main.kt:169)
        at org.jetbrains.dokka.gradle.DokkaTask.generate(main.kt:96)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:228)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:221)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:210)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:621)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:604)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 14 more
```

This is using version 0.9.9. I noticed some work being done using M03 (https://github.com/Kotlin/dokka/pull/117), but I'm not sure if that fixes this.

**Comment by semoro** [comment]
Dokka 0.9.10 will fix this problem. Also see note in Readme, if you want use dokka 0.9.9 with kotlin 1.1-M3 please use gradle 3.2 as temporary workaround. Otherwise you may want to wait until 0.9.10 release, which will be on that week(I hope)

**Comment by nhaarman** [comment]
Ah, I missed that part. I did a search on 'M03' in the issues. Thanks!
