### ISSUE TITLE
Errors during attempted migration of dokkaGfm to 1.4 API

### ISSUE THREAD

**Issue by yschimke** [Kotlin/dokka#1592]
```
Caused by: java.lang.IllegalArgumentException: Count 'n' must be non-negative, but was -1.
        at kotlin.text.StringsKt__StringsJVMKt.repeat(StringsJVM.kt:662)
        at org.jetbrains.dokka.gfm.CommonmarkRenderer.buildTable(GfmPlugin.kt:217)
        at org.jetbrains.dokka.gfm.CommonmarkRenderer.buildTable(GfmPlugin.kt:51)
        at org.jetbrains.dokka.base.renderers.DefaultRenderer.buildContentNode(DefaultRenderer.kt:117)
        at org.jetbrains.dokka.base.renderers.DefaultRenderer.build(DefaultRenderer.kt:100)
        at org.jetbrains.dokka.base.renderers.DefaultRenderer$buildGroup$1.invoke(DefaultRenderer.kt:63)
        at org.jetbrains.dokka.base.renderers.DefaultRenderer$buildGroup$1.invoke(DefaultRenderer.kt:19)
        at org.jetbrains.dokka.gfm.CommonmarkRenderer.wrapGroup(GfmPlugin.kt:72)
        at org.jetbrains.dokka.gfm.CommonmarkRenderer.wrapGroup(GfmPlugin.kt:51)
        at org.jetbrains.dokka.base.renderers.DefaultRenderer.buildGroup(DefaultRenderer.kt:63)
        at org.jetbrains.dokka.base.renderers.DefaultRenderer.buildContentNode(DefaultRenderer.kt:118)
        at org.jetbrains.dokka.base.renderers.DefaultRenderer.build(DefaultRenderer.kt:100)
        at org.jetbrains.dokka.base.renderers.DefaultRenderer$buildGroup$1.invoke(DefaultRenderer.kt:63)
        at org.jetbrains.dokka.base.renderers.DefaultRenderer$buildGroup$1.invoke(DefaultRenderer.kt:19)
        at org.jetbrains.dokka.gfm.CommonmarkRenderer.wrapGroup(GfmPlugin.kt:72)
        at org.jetbrains.dokka.gfm.CommonmarkRenderer.wrapGroup(GfmPlugin.kt:51)
        at org.jetbrains.dokka.base.renderers.DefaultRenderer.buildGroup(DefaultRenderer.kt:63)
        at org.jetbrains.dokka.base.renderers.DefaultRenderer.buildContentNode(DefaultRenderer.kt:118)
        at org.jetbrains.dokka.base.renderers.DefaultRenderer.build(DefaultRenderer.kt:100)
        at org.jetbrains.dokka.base.renderers.DefaultRenderer$buildGroup$1.invoke(DefaultRenderer.kt:63)
        at org.jetbrains.dokka.base.renderers.DefaultRenderer$buildGroup$1.invoke(DefaultRenderer.kt:19)
        at org.jetbrains.dokka.gfm.CommonmarkRenderer.wrapGroup(GfmPlugin.kt:72)
        at org.jetbrains.dokka.gfm.CommonmarkRenderer.wrapGroup(GfmPlugin.kt:51)
        at org.jetbrains.dokka.base.renderers.DefaultRenderer.buildGroup(DefaultRenderer.kt:63)
        at org.jetbrains.dokka.base.renderers.DefaultRenderer.buildContentNode(DefaultRenderer.kt:118)
        at org.jetbrains.dokka.base.renderers.DefaultRenderer.build(DefaultRenderer.kt:100)
        at org.jetbrains.dokka.base.renderers.DefaultRenderer$buildGroup$1.invoke(DefaultRenderer.kt:63)
        at org.jetbrains.dokka.base.renderers.DefaultRenderer$buildGroup$1.invoke(DefaultRenderer.kt:19)
        at org.jetbrains.dokka.gfm.CommonmarkRenderer.wrapGroup(GfmPlugin.kt:72)
        at org.jetbrains.dokka.gfm.CommonmarkRenderer.wrapGroup(GfmPlugin.kt:51)
        at org.jetbrains.dokka.base.renderers.DefaultRenderer.buildGroup(DefaultRenderer.kt:63)
        at org.jetbrains.dokka.base.renderers.DefaultRenderer.buildContentNode(DefaultRenderer.kt:118)
        at org.jetbrains.dokka.gfm.CommonmarkRenderer$buildDivergent$distinct$2.invoke(GfmPlugin.kt:261)
        at org.jetbrains.dokka.gfm.CommonmarkRenderer$buildDivergent$distinct$2.invoke(GfmPlugin.kt:51)
        at org.jetbrains.dokka.base.renderers.DefaultRenderer.groupDivergentInstances(DefaultRenderer.kt:213)
        at org.jetbrains.dokka.gfm.CommonmarkRenderer.buildDivergent(GfmPlugin.kt:255)
        at org.jetbrains.dokka.gfm.CommonmarkRenderer.buildDivergent(GfmPlugin.kt:51)
        at org.jetbrains.dokka.base.renderers.DefaultRenderer.buildContentNode(DefaultRenderer.kt:121)
        at org.jetbrains.dokka.base.renderers.DefaultRenderer.build(DefaultRenderer.kt:100)
        at org.jetbrains.dokka.base.renderers.DefaultRenderer$buildGroup$1.invoke(DefaultRenderer.kt:63)
        at org.jetbrains.dokka.base.renderers.DefaultRenderer$buildGroup$1.invoke(DefaultRenderer.kt:19)
        at org.jetbrains.dokka.gfm.CommonmarkRenderer.wrapGroup(GfmPlugin.kt:72)
        at org.jetbrains.dokka.gfm.CommonmarkRenderer.wrapGroup(GfmPlugin.kt:51)
        at org.jetbrains.dokka.base.renderers.DefaultRenderer.buildGroup(DefaultRenderer.kt:63)
        at org.jetbrains.dokka.base.renderers.DefaultRenderer.buildContentNode(DefaultRenderer.kt:118)
        at org.jetbrains.dokka.base.renderers.DefaultRenderer.build(DefaultRenderer.kt:100)
        at org.jetbrains.dokka.base.renderers.DefaultRenderer.build$default(DefaultRenderer.kt:98)
        at org.jetbrains.dokka.base.renderers.DefaultRenderer.buildPageContent(DefaultRenderer.kt:158)
        at org.jetbrains.dokka.gfm.CommonmarkRenderer$renderPage$2.invoke(GfmPlugin.kt:340)
        at org.jetbrains.dokka.gfm.CommonmarkRenderer$renderPage$2.invoke(GfmPlugin.kt:51)
        at org.jetbrains.dokka.gfm.CommonmarkRenderer.buildPage(GfmPlugin.kt:245)
        at org.jetbrains.dokka.gfm.CommonmarkRenderer.renderPage$suspendImpl(GfmPlugin.kt:340)
        at org.jetbrains.dokka.gfm.CommonmarkRenderer.renderPage(GfmPlugin.kt)
        at org.jetbrains.dokka.base.renderers.DefaultRenderer$renderPages$2.invokeSuspend(DefaultRenderer.kt:185)
        at org.jetbrains.dokka.base.renderers.DefaultRenderer$renderPages$2.invoke(DefaultRenderer.kt)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
        at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:194)
        at org.jetbrains.dokka.base.renderers.DefaultRenderer.renderPages(DefaultRenderer.kt:184)
        at org.jetbrains.dokka.base.renderers.DefaultRenderer$renderPages$2$invokeSuspend$$inlined$forEach$lambda$1.invokeSuspend(DefaultRenderer.kt:188)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

Attemting upgrade here https://github.com/square/okhttp/pull/6342

Fails with 

```
$ .\gradlew okhttp:dokkaGfm --stacktrace
```

**Comment by yschimke** [comment]
Failing on content like

```
This URL's fragment, like "abc" for http://host/#abc. This is null if the URL has no fragment.

  
|  URL fragment()| 
|---|
| <a name="okhttp3/HttpUrl/fragment/#/PointingToDeclaration/"></a>http://host/| <a name="okhttp3/HttpUrl/fragment/#/PointingToDeclaration/"></a>null
```

**Comment by yschimke** [comment]
However the source content is

```
  /**
   * This URL's fragment, like `"abc"` for `http://host/#abc`. This is null if the URL has no
   * fragment.
   *
   * | URL                    | `fragment()` |
   * | :--------------------- | :----------- |
   * | `http://host/`         | nulls         |
   * | `http://host/#`        | `""`         |
   * | `http://host/#abc`     | `"abc"`      |
   * | `http://host/#abc|def` | `"abc|def"`  |
   */
  @get:JvmName("fragment") val fragment: String?,
```

**Comment by yschimke** [comment]
~Seems to be failing because the size of the header in rows is compared with the size of the row in width.

https://github.com/Kotlin/dokka/blame/0235c0ee12deaffed1d69ebaad86d24e5e48d9df/plugins/gfm/src/main/kotlin/GfmPlugin.kt#L217

I suspect a simple fix is to guard against calling repeat with negative values anyway, but the correct fix is to compare both widths.
