### ISSUE TITLE
Not compatible with Android Gradle plugin 3.0.0-alpha3

### ISSUE THREAD

**Issue by gabrielittner** [Kotlin/dokka#168]
Getting this execption during configuration: 
```
Caused by: java.lang.NoSuchMethodError: com.android.build.gradle.internal.core.GradleVariantConfiguration.getCompileClasspath()Ljava/util/Set;
        at org.jetbrains.dokka.gradle.AndroidSdkProvider$allVariantsClassPath$2.invoke(mainAndroid.kt:49)
        at org.jetbrains.dokka.gradle.AndroidSdkProvider$allVariantsClassPath$2.invoke(mainAndroid.kt:26)
        at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:130)
        at org.jetbrains.dokka.gradle.AndroidSdkProvider.getAllVariantsClassPath(mainAndroid.kt)
        at org.jetbrains.dokka.gradle.AndroidSdkProvider.getClasspath(mainAndroid.kt:61)
        at org.jetbrains.dokka.gradle.DokkaTask.generate(main.kt:165)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.doExecute(DefaultTaskClassInfoStore.java:141)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:121)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:711)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:694)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:122)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:303)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:295)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:177)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:111)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
        ... 27 more
```

**Comment by semoro** [comment]
Fixed in [0.9.15](https://github.com/Kotlin/dokka/releases/tag/0.9.15)
