### ISSUE TITLE
Empty collection can't be reduced exception with 1.4.20

### ISSUE THREAD

**Issue by ZacSweers** [Kotlin/dokka#1686]
**Describe the bug**
When running `dokkaHtml` on the linked reproducer project, I get this failure:

```
Caused by: java.lang.UnsupportedOperationException: Empty collection can't be reduced.
        at org.jetbrains.dokka.base.transformers.documentables.DefaultDocumentableMerger.invoke(DefaultDocumentableMerger.kt:287)
        at org.jetbrains.dokka.DokkaGenerator.mergeDocumentationModels(DokkaGenerator.kt:95)
        at org.jetbrains.dokka.DokkaGenerator$generate$1.invoke(DokkaGenerator.kt:42)
        at org.jetbrains.dokka.DokkaGenerator$generate$1.invoke(DokkaGenerator.kt:22)
        at org.jetbrains.dokka.DokkaGeneratorKt.timed(DokkaGenerator.kt:184)
        at org.jetbrains.dokka.DokkaGeneratorKt.access$timed(DokkaGenerator.kt:1)
        at org.jetbrains.dokka.DokkaGenerator.generate(DokkaGenerator.kt:26)
        at org.jetbrains.dokka.DokkaBootstrapImpl.generate(DokkaBootstrapImpl.kt:78)
        at org.jetbrains.dokka.gradle.DelegatedInvocationHandler.invoke(automagicTypedProxy.kt:41)

```

**Expected behaviour**
It should not crash

**Screenshots**
N/A

**To Reproduce**
https://github.com/slackhq/keeper and run `./gradlew -p keeper-gradle-plugin dokkaHtml`

**Dokka configuration**
Configuration of dokka used to reproduce the bug

```kotlin
tasks.named<DokkaTask>("dokkaHtml") {
  outputDirectory.set(rootDir.resolve("../docs/0.x"))
  dokkaSourceSets.configureEach {
    skipDeprecated.set(true)
    externalDocumentationLink {
      url.set(URL("https://docs.gradle.org/${gradle.gradleVersion}/javadoc/index.html"))
    }
    externalDocumentationLink {
      packageListUrl.set(URL("https://developer.android.com/reference/tools/gradle-api/package-list"))
      url.set(URL("https://developer.android.com/reference/tools/gradle-api/"))
    }

    // Suppress Zipflinger copy
    perPackageOption {
      // TODO re-enable this with a proper regex
//      matchingRegex.set("com.slack.keeper.internal.zipflinger")
      suppress.set(true)
    }
  }
}
```

**Installation**
- Operating system: macOS Big Sur
- Build tool: Gradle v6.8-rc4
- Dokka version: 1.4.20

**Additional context**
None

**Comment by ZacSweers** [comment]
Figured it out, something about leaving the packaging options block partially enabled threw it off
