### ISSUE TITLE
Execution failed for task ':library:dokkaGfml'. > java.net.SocketTimeoutException: connect timed out

### ISSUE THREAD

**Issue by wdziemia** [Kotlin/dokka#1762]
**Describe the bug**

Looks like the Dokka task is timing out when trying to resolve package-lists.

https://github.com/Kotlin/dokka/blob/3cb4702a68139788de6e1f7b087ced345f2b71ba/plugins/base/src/main/kotlin/resolvers/shared/PackageList.kt#L17

```
* What went wrong:
Execution failed for task ':purr:dokkaGfm'.
> java.net.SocketTimeoutException: connect timed out

...

Caused by: java.net.SocketTimeoutException: connect timed out
	at org.jetbrains.dokka.base.resolvers.shared.UtilsKt$readContent$1.invoke(utils.kt:16)
	at org.jetbrains.dokka.base.resolvers.shared.UtilsKt.readContent(utils.kt:36)
	at org.jetbrains.dokka.base.resolvers.shared.UtilsKt.readContent$default(utils.kt:8)
	at org.jetbrains.dokka.base.resolvers.shared.PackageList$Companion.load(PackageList.kt:17)
	at org.jetbrains.dokka.base.resolvers.local.DefaultLocationProvider.<init>(DefaultLocationProvider.kt:28)
	at org.jetbrains.dokka.base.resolvers.local.DokkaBaseLocationProvider.<init>(DokkaBaseLocationProvider.kt:13)
	at org.jetbrains.dokka.base.resolvers.local.DokkaLocationProvider.<init>(DokkaLocationProvider.kt:18)
	at org.jetbrains.dokka.gfm.MarkdownLocationProvider.<init>(GfmPlugin.kt:370)
	at org.jetbrains.dokka.gfm.MarkdownLocationProviderFactory.getLocationProvider(GfmPlugin.kt:364)
	at org.jetbrains.dokka.gfm.MarkdownLocationProviderFactory.getLocationProvider(GfmPlugin.kt:362)
	at org.jetbrains.dokka.base.renderers.PackageListService.createPackageList(PackageListService.kt:19)
	at org.jetbrains.dokka.base.renderers.PackageListCreator.packageList(preprocessors.kt:27)
	at org.jetbrains.dokka.base.renderers.PackageListCreator.invoke(preprocessors.kt:22)
	at org.jetbrains.dokka.base.renderers.DefaultRenderer.render(DefaultRenderer.kt:197)
	at org.jetbrains.dokka.DokkaGenerator.render(DokkaGenerator.kt:126)
	at org.jetbrains.dokka.DokkaGenerator$generate$1.invoke(DokkaGenerator.kt:54)
	at org.jetbrains.dokka.DokkaGenerator$generate$1.invoke(DokkaGenerator.kt:22)
	at org.jetbrains.dokka.DokkaGeneratorKt.timed(DokkaGenerator.kt:184)
	at org.jetbrains.dokka.DokkaGeneratorKt.access$timed(DokkaGenerator.kt:1)
	at org.jetbrains.dokka.DokkaGenerator.generate(DokkaGenerator.kt:26)
	at org.jetbrains.dokka.DokkaBootstrapImpl.generate(DokkaBootstrapImpl.kt:78)
	at org.jetbrains.dokka.gradle.DelegatedInvocationHandler.invoke(automagicTypedProxy.kt:41)
	at com.sun.proxy.$Proxy218.generate(Unknown Source)
	at org.jetbrains.dokka.gradle.AbstractDokkaTask.generateDocumentation$gradle_plugin(AbstractDokkaTask.kt:86)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)
	... 119 more

```

**Expected behaviour**
I expect an exception to be caught and links stripped from docs when a single request fails. Retry logic would be handy too but we had multiple failures in a row over the course of 4 hours so not sure how much that would do.

**To Reproduce**
I am having trouble reproducing this locally on my machine. This is only happening on our CI, Bitrise. 

**Dokka configuration**

we are executing `dokkaGfm` configured with the following:

```kotlin
tasks.withType<org.jetbrains.dokka.gradle.DokkaTask>().configureEach {
    outputDirectory.set(file("$rootDir/docs/dokka"))
}
```

**Installation**
- Operating system: macOS
- Build tool: Gradle v6.8.3
- Dokka version: 1.4.20

**Additional context**

The hosts Im seeing from the diff between the `offlineMode` being set to false is the following:
`https://kotlinlang.org`
`https://docs.oracle.com/`
`https://developer.android.com/reference/`

Ive set flag `offlineMode` to false in order to not resolve package-list and avoid the exception from failing the task.

**Comment by MarcinAman** [comment]
Hi, in the newest release this will result in a warning rather than error: https://github.com/Kotlin/dokka/blob/7cf644f064868934fe8dcb46ab150f25fab8e8c8/plugins/base/src/main/kotlin/resolvers/shared/PackageList.kt#L17

I don't have a set date for the release but it is coming soon ☺️

**Comment by MarcinAman** [comment]
If you want to grab the changes right now you can add our dev repository: `maven("https://maven.pkg.jetbrains.space/kotlin/p/dokka/dev")` and use latest version like: `1.4.20.2-dev-74`

**Comment by wdziemia** [comment]
@MarcinAman thank you!!
