### ISSUE TITLE
Unstable source sets hashcode between single- and multi-module tasks

### ISSUE THREAD

**Issue by kamildoleglo** [Kotlin/dokka#1943]
**Describe the bug**
hashCode() present in anchors is unstable between single-module and multi-module tasks due to the task path being present in the sourceSetID

**Expected behaviour**
hashCode() for sourcesets should be the same 

**Installation**
- Build tool: Gradle 
- Dokka version: 1.4.30

**Comment by solo-md** [comment]
Hi @kamildoleglo 
I have sometimes (not always) build failures with the next Stack Trace. Could that be because of the issue you've mentioned?
I'm using kotlin 1.4.32, dokka cli 1.4.32
`
     [java] PROGRESS: Validity check
     [java] PROGRESS: Creating documentation models
     [java] WARN: The registry key 'java.correct.class.type.by.place.resolve.scope' accessed, but not loaded yet
     [java] PROGRESS:
     [java] Exception in thread "main" java.lang.IllegalArgumentException: Equal objects must have equal hashcodes. During rehashing, Trove discovered that the following two objects claim to be equal (as in java.lang.Object.equals() or TObjectHashingStrategy.equals()) but their hashCodes (or those calculated by your TObjectHashingStrategy) are not equal.This violates the general contract of java.lang.Object.hashCode().  See bullet point two in that method's documentation. object #1 =com (class org.jetbrains.kotlin.name.FqName), hashCode=98689; object #2 =com (class org.jetbrains.kotlin.name.FqName), hashCode=98689
     [java]     at gnu.trove.TObjectHash.throwObjectContractViolation(TObjectHash.java:331)
     [java]     at gnu.trove.THashMap.rehash(THashMap.java:347)
     [java]     at gnu.trove.THash.postInsertHook(THash.java:286)
     [java]     at gnu.trove.THashMap.put(THashMap.java:174)
     [java]     at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCliJavaFileManagerImpl.findVirtualFileForTopLevelClass(KotlinCliJavaFileManagerImpl.kt:306)
     [java]     at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCliJavaFileManagerImpl.access$findVirtualFileForTopLevelClass(KotlinCliJavaFileManagerImpl.kt:48)
     [java]     at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCliJavaFileManagerImpl$findPsiClass$1.invoke(KotlinCliJavaFileManagerImpl.kt:70)
     [java]     at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCliJavaFileManagerImpl$findPsiClass$1.invoke(KotlinCliJavaFileManagerImpl.kt:69)
     [java]     at org.jetbrains.kotlin.util.PerformanceCounter.time(PerformanceCounter.kt:101)
     [java]     at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCliJavaFileManagerImpl.findPsiClass(KotlinCliJavaFileManagerImpl.kt:69)
     [java]     at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCliJavaFileManagerImpl.findClass(KotlinCliJavaFileManagerImpl.kt:135)
     [java]     at com.intellij.psi.impl.PsiElementFinderImpl.findClass(PsiElementFinderImpl.java:49)
     [java]     at com.intellij.psi.impl.JavaPsiFacadeImpl.doFindClass(JavaPsiFacadeImpl.java:96)
     [java]     at com.intellij.psi.impl.JavaPsiFacadeImpl.findClass(JavaPsiFacadeImpl.java:73)
     [java]     at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.resolve(PsiJavaCodeReferenceElementImpl.java:440)
     [java]     at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.access$100(PsiJavaCodeReferenceElementImpl.java:44)
     [java]     at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:375)
     [java]     at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:368)
     [java]     at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolveWithCaching$2(ResolveCache.java:185)
     [java]     at com.intellij.openapi.util.Computable.get(Computable.java:17)
     [java]     at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$3(ResolveCache.java:227)
     [java]     at com.intellij.openapi.util.RecursionManager$1.doPreventingRecursion(RecursionManager.java:112)
     [java]     at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:71)
     [java]     at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:204)
     [java]     at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:185)
     [java]     at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:802)
     [java]     at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:794)
     [java]     at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.multiResolve(PsiJavaCodeReferenceElementImpl.java:423)
     [java]     at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.advancedResolve(PsiJavaCodeReferenceElementImpl.java:417)
     [java]     at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.resolve(PsiJavaCodeReferenceElementImpl.java:352)
     [java]     at com.intellij.psi.impl.source.PsiImportStatementBaseImpl.resolve(PsiImportStatementBaseImpl.java:64)
     [java]     at com.intellij.psi.impl.source.PsiJavaFileBaseImpl.findExplicitDeclarations(PsiJavaFileBaseImpl.java:333)
     [java]     at com.intellij.psi.impl.source.PsiJavaFileBaseImpl.lambda$getExplicitlyEnumeratedDeclarations$0(PsiJavaFileBaseImpl.java:317)
     [java]     at com.intellij.openapi.util.VolatileNotNullLazyValue$1.compute(VolatileNotNullLazyValue.java:56)
     [java]     at com.intellij.openapi.util.VolatileNotNullLazyValue.getValue(VolatileNotNullLazyValue.java:36)
     [java]     at com.intellij.psi.impl.source.PsiJavaFileBaseImpl.lambda$getExplicitlyEnumeratedDeclarations$1(PsiJavaFileBaseImpl.java:318)
     [java]     at com.intellij.util.containers.ContainerUtil.process(ContainerUtil.java:905)
     [java]     at com.intellij.psi.impl.source.PsiJavaFileBaseImpl.processDeclarations(PsiJavaFileBaseImpl.java:273)
     [java]     at com.intellij.psi.scope.util.PsiScopesUtil.treeWalkUp(PsiScopesUtil.java:75)
     [java]     at com.intellij.psi.scope.util.PsiScopesUtil.treeWalkUp(PsiScopesUtil.java:54)
     [java]     at com.intellij.psi.scope.util.PsiScopesUtil.resolveAndWalk(PsiScopesUtil.java:221)
     [java]     at com.intellij.psi.scope.util.PsiScopesUtil.resolveAndWalk(PsiScopesUtil.java:150)
     [java]     at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.resolve(PsiJavaCodeReferenceElementImpl.java:489)
     [java]     at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.access$100(PsiJavaCodeReferenceElementImpl.java:44)
     [java]     at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:375)
     [java]     at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:368)
     [java]     at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolveWithCaching$2(ResolveCache.java:185)
     [java]     at com.intellij.openapi.util.Computable.get(Computable.java:17)
     [java]     at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$3(ResolveCache.java:227)
     [java]     at com.intellij.openapi.util.RecursionManager$1.doPreventingRecursion(RecursionManager.java:112)
     [java]     at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:71)
     [java]     at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:204)
     [java]     at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:185)
     [java]     at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:802)
     [java]     at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.getCanonicalText(PsiJavaCodeReferenceElementImpl.java:290)
     [java]     at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.getCanonicalText(PsiJavaCodeReferenceElementImpl.java:280)
     [java]     at com.intellij.psi.impl.source.PsiClassReferenceType.getText(PsiClassReferenceType.java:241)
     [java]     at com.intellij.psi.impl.source.PsiClassReferenceType.getCanonicalText(PsiClassReferenceType.java:228)
     [java]     at com.intellij.psi.PsiArrayType.getCanonicalText(PsiArrayType.java:40)
     [java]     at com.intellij.psi.PsiType$Stub.getCanonicalText(PsiType.java:354)
     [java]     at org.jetbrains.dokka.base.translators.psi.DefaultPsiToDocumentableTranslator$DokkaPsiParser.getBound(DefaultPsiToDocumentableTranslator.kt:472)
     [java]     at org.jetbrains.dokka.base.translators.psi.DefaultPsiToDocumentableTranslator$DokkaPsiParser.parseFunction(DefaultPsiToDocumentableTranslator.kt:389)
     [java]     at org.jetbrains.dokka.base.translators.psi.DefaultPsiToDocumentableTranslator$DokkaPsiParser.parseFunction$default(DefaultPsiToDocumentableTranslator.kt:357)
     [java]     at org.jetbrains.dokka.base.translators.psi.DefaultPsiToDocumentableTranslator$DokkaPsiParser$parseClasslike$2$invokeSuspend$$inlined$with$lambda$3$1$1.invokeSuspend(parallelCollectionOperations.kt:19)
     [java]     at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
     [java]     at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
     [java]     at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
     [java]     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
     [java]     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
     [java]     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
`

**Comment by IgnatBeresnev** [comment]
It's unclear if it's a blocker for stdlib's migration. @d-ambatenne will have a look at Google analytics to see how popular anchor links are.

An example of an anchor link: `https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/#966740715%2FClasslikes%2F1975948010`
