### ISSUE TITLE
Concurrency Exceptions: unsafe parallel use of HashMap (Trove and FileWriter)

### ISSUE THREAD

**Issue by owengray-google** [Kotlin/dokka#2052]
(Dokka ~1.5.0-dev-104)
One of these issues is in Trove, the other appears to be in `org.jetbrains.dokka.base.renderers.FileWriter.write(FileWriter.kt:21)`.

4 times in the last 60 days (based on a search regex for the specific error message, may be an underestimate for all trove-related exceptions):
```
at com.intellij.openapi.diagnostic.DefaultLogger.error(DefaultLogger.java:53)
at com.intellij.openapi.diagnostic.Logger.error(Logger.java:143)
at com.intellij.util.IdempotenceChecker.reportFailure(IdempotenceChecker.java:92)
at com.intellij.util.IdempotenceChecker.checkEquivalence(IdempotenceChecker.java:79)
at com.intellij.psi.impl.source.resolve.ResolveCache.cache(ResolveCache.java:288)
at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:216)
at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:185)
at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:802)
at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:794)
at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.multiResolve(PsiJavaCodeReferenceElementImpl.java:423)
at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.advancedResolve(PsiJavaCodeReferenceElementImpl.java:417)
at com.intellij.psi.impl.source.PsiClassReferenceType.resolveGenerics(PsiClassReferenceType.java:177)
at com.intellij.psi.impl.source.PsiClassReferenceType.resolve(PsiClassReferenceType.java:121)
at com.intellij.psi.util.TypeConversionUtil$2.visitClassType(TypeConversionUtil.java:1283)
at com.intellij.psi.util.TypeConversionUtil$2.visitClassType(TypeConversionUtil.java:1274)
at com.intellij.psi.PsiClassType.accept(PsiClassType.java:224)
at com.intellij.psi.util.TypeConversionUtil.erasure(TypeConversionUtil.java:1274)
at com.intellij.psi.util.MethodSignatureUtil.calcErasedParameterTypes(MethodSignatureUtil.java:90)
at com.intellij.psi.util.MethodSignatureBase.getErasedParameterTypes(MethodSignatureBase.java:77)
at com.intellij.psi.util.MethodSignatureBase.hashCode(MethodSignatureBase.java:92)
at com.intellij.psi.util.MethodSignatureUtil$2.computeHashCode(MethodSignatureUtil.java:52)
at com.intellij.psi.util.MethodSignatureUtil$2.computeHashCode(MethodSignatureUtil.java:49)
at gnu.trove.TObjectHash.insertionIndex(TObjectHash.java:224)
at gnu.trove.THashMap.put(THashMap.java:164)
at com.intellij.psi.impl.PsiSuperMethodImplUtil.buildMethodHierarchy(PsiSuperMethodImplUtil.java:173)
at com.intellij.psi.impl.PsiSuperMethodImplUtil.lambda$static$1(PsiSuperMethodImplUtil.java:34)
at com.intellij.util.containers.ConcurrentFactoryMap$2.create(ConcurrentFactoryMap.java:174)
at com.intellij.util.containers.ConcurrentFactoryMap.get(ConcurrentFactoryMap.java:40)
at com.intellij.psi.impl.PsiSuperMethodImplUtil.lambda$getHierarchicalMethodSignature$3(PsiSuperMethodImplUtil.java:356)
at com.intellij.util.containers.ConcurrentFactoryMap$2.create(ConcurrentFactoryMap.java:174)
at com.intellij.util.containers.ConcurrentFactoryMap.get(ConcurrentFactoryMap.java:40)
at com.intellij.psi.impl.PsiSuperMethodImplUtil.getHierarchicalMethodSignature(PsiSuperMethodImplUtil.java:365)
at com.intellij.psi.impl.PsiSuperMethodImplUtil.getHierarchicalMethodSignature(PsiSuperMethodImplUtil.java:345)
at com.intellij.psi.impl.source.PsiMethodImpl.getHierarchicalMethodSignature(PsiMethodImpl.java:140)
at com.intellij.psi.impl.search.MethodSuperSearcher.processQuery(MethodSuperSearcher.java:31)
at com.intellij.psi.impl.search.MethodSuperSearcher.processQuery(MethodSuperSearcher.java:19)
at com.intellij.openapi.application.QueryExecutorBase.execute(QueryExecutorBase.java:77)
at com.intellij.util.ExecutorsQuery.processResults(ExecutorsQuery.java:28)
at com.intellij.util.AbstractQuery.doProcessResults(AbstractQuery.java:96)
at com.intellij.util.AbstractQuery.delegateProcessResults(AbstractQuery.java:119)
at com.intellij.util.UniqueResultsQuery.processResults(UniqueResultsQuery.java:35)
at com.intellij.util.AbstractQuery.doProcessResults(AbstractQuery.java:96)
at com.intellij.util.AbstractQuery.forEach(AbstractQuery.java:88)
at com.intellij.util.AbstractQuery.findAll(AbstractQuery.java:30)
at com.intellij.psi.impl.PsiSuperMethodImplUtil.findSuperMethodSignatures(PsiSuperMethodImplUtil.java:72)
at com.intellij.psi.impl.PsiSuperMethodImplUtil.findSuperMethodsInternal(PsiSuperMethodImplUtil.java:56)
at com.intellij.psi.impl.PsiSuperMethodImplUtil.findSuperMethods(PsiSuperMethodImplUtil.java:51)
at com.intellij.psi.impl.PsiSuperMethodImplUtil.findSuperMethods(PsiSuperMethodImplUtil.java:41)
at com.intellij.psi.impl.source.PsiMethodImpl.findSuperMethods(PsiMethodImpl.java:92)
at org.jetbrains.dokka.base.translators.psi.DefaultPsiToDocumentableTranslator$DokkaPsiParser$parseClasslike$2.invokeSuspend(DefaultPsiToDocumentableTranslator.kt:214)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: java.lang.Throwable: Non-idempotent computation: it returns different results when invoked multiple times or on different threads:
1 != 0
which is length of [ClassCandidateInfo{element=PsiClass:FocusHighlightHandler, substitutor=EmptySubstitutor}] and []

Recomputation gives [Lcom.intellij.psi.JavaResolveResult;@504f163b (class [Lcom.intellij.psi.JavaResolveResult;) which is equivalent to 'fresh'
Recomputation log:
Resolving PsiJavaCodeReferenceElement:FocusHighlightHandler of class com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':docs-public:dackkaDocs'.
> A failure occurred while executing androidx.build.dackka.DackkaWorkAction
> Process 'command '$CHECKOUT/prebuilts/jdk/jdk11/linux-x86/bin/java'' finished with non-zero exit value 1

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':docs-public:dackkaDocs'.
Caused by: org.gradle.workers.internal.DefaultWorkerExecutor$WorkExecutionException: A failure occurred while executing androidx.build.dackka.DackkaWorkAction
Caused by: org.gradle.process.internal.ExecException: Process 'command '$CHECKOUT/prebuilts/jdk/jdk11/linux-x86/bin/java'' finished with non-zero exit value 1
at androidx.build.dackka.DackkaWorkAction.execute(DackkaTask.kt:153)
```
It looks like it might be possible to prevent this error without changes in trove, by making PSI more threadsafe and deterministic? Though that could easily be a red herring and/or more difficult.

13 times in the last 60 days (with this exact cast in the error message):
```
Detected these failing tasks: [':docs-tip-of-tree:dackkaDocs']
> Task :docs-tip-of-tree:dackkaDocs
ERROR: Failed to write org.jetbrains.dokka.base.renderers.FileWriter@22116b48. Parent job is Cancelling
kotlinx.coroutines.JobCancellationException: Parent job is Cancelling; job=ScopeCoroutine{Cancelling}@4edf3cb3
Caused by: java.lang.ClassCastException: class java.util.LinkedHashMap$Entry cannot be cast to class java.util.HashMap$TreeNode (java.util.LinkedHashMap$Entry and java.util.HashMap$TreeNode are in module java.base of loader 'bootstrap')
	at org.jetbrains.dokka.base.renderers.FileWriter.write(FileWriter.kt:21)
	at com.google.devsite.renderer.impl.PackageRenderer.writeClasslike(PackageRenderer.kt:91)
	at com.google.devsite.renderer.impl.PackageRenderer$writeClasslike$1.invokeSuspend(PackageRenderer.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
ERROR: Failed to write org.jetbrains.dokka.base.renderers.FileWriter@22116b48. Parent job is Cancelling
kotlinx.coroutines.JobCancellationException: Parent job is Cancelling; job=BlockingCoroutine{Cancelling}@9b75812
Caused by: java.lang.ClassCastException: class java.util.LinkedHashMap$Entry cannot be cast to class java.util.HashMap$TreeNode (java.util.LinkedHashMap$Entry and java.util.HashMap$TreeNode are in module java.base of loader 'bootstrap')
	at org.jetbrains.dokka.base.renderers.FileWriter.write(FileWriter.kt:21)
	at com.google.devsite.renderer.impl.PackageRenderer.writeClasslike(PackageRenderer.kt:91)
	at com.google.devsite.renderer.impl.PackageRenderer$writeClasslike$1.invokeSuspend(PackageRenderer.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Exception in thread "main" java.lang.ClassCastException: class java.util.LinkedHashMap$Entry cannot be cast to class java.util.HashMap$TreeNode (java.util.LinkedHashMap$Entry and java.util.HashMap$TreeNode are in module java.base of loader 'bootstrap')
	at org.jetbrains.dokka.base.renderers.FileWriter.write(FileWriter.kt:21)
	at com.google.devsite.renderer.impl.PackageRenderer.writeClasslike(PackageRenderer.kt:91)
	at com.google.devsite.renderer.impl.PackageRenderer$writeClasslike$1.invokeSuspend(PackageRenderer.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```
[This stackoverflow issue](https://stackoverflow.com/questions/29967401/strange-hashmap-exception-hashmapnode-cannot-be-cast-to-hashmaptreenode/29971168) is what makes me think the second one is concurrency related.

It looks like this might be related to us invoking this suspend function in a parallel way.
I suspect the fix might look something like changing 
```
package org.jetbrains.dokka.base.renderers

class FileWriter(val context: DokkaContext): OutputWriter {
    private val createdFiles: MutableSet<String> = mutableSetOf()
```
to use a ConcurrentHashSet equivalent (`ConcurrentHashMap.newKeySet()`).

**Comment by vmishenev** [comment]
The first stack trace deserves another issue. I will discuss it with a code analysis team.
