### ISSUE TITLE
Classpath conflict with cli runner

### ISSUE THREAD

**Issue by kggilmer** [Kotlin/dokka#2186]
**Describe the bug**
When running the cli runner, classpath errors[1] are thrown by types bundled in the core module, however when the core module is added to the classpath, the following error is thrown and the program exits:

```
Exception in thread "main" java.lang.AssertionError: Dokka API found on plugins classpath. This will lead to subtle bugs. Please fix your plugins dependencies or exclude dokka api artifact from plugin classpath
	at org.jetbrains.dokka.plugability.DokkaContextKt.checkClasspath(DokkaContext.kt:220)
	at org.jetbrains.dokka.plugability.DokkaContextKt.access$checkClasspath(DokkaContext.kt:1)
```

1:
```
PROGRESS: 
Exception in thread "main" java.lang.NoClassDefFoundError: org/jetbrains/dokka/model/ComplexExpression
	at org.jetbrains.dokka.base.translators.descriptors.DokkaDescriptorVisitor.toDefaultValueExpression(DefaultDescriptorToDocumentableTranslator.kt:1039)
...
```

**Expected behaviour**
There is a documented configuration that allows the cli runner to complete successfully.

**Screenshots**
If applicable, add screenshots to help explain your problem

**To Reproduce**
1. Build dokka from HEAD (I'm on bc68cbfb1e2644498559016889b838a7b2836e41)
2. run `gradlew jars` and copy all jars into same dir as the cli JAR
3. run the cli runner:
```
java -jar dokka-cli-1.5.31.jar -pluginsClasspath "base-1.6.0-SNAPSHOT.jar;kotlin-analysis-1.6.0-SNAPSHOT.jar;dokka-kotlin-analysis-compiler-1.6.0-SNAPSHOT.jar;dokka-kotlin-analysis-intellij-1.6.0-SNAPSHOT.jar" -sourceSet "-src /somepath"
```

**Dokka configuration**

See above

**Installation**
- Operating system: Linux
- Build tool: cli
- Dokka version: HEAD

**Additional context**
Add any other context about the problem here

**Are you willing to provide a PR?**
Providing a PR can drastically speed up the process of fixing this bug

**Comment by vmishenev** [comment]
We use `dokka-cli` of 1.5.31 version but `pluginsClasspath` has another version 1.6.
They are incompatible. Use  `dokka-cli` and `pluginsClasspath` with the same version.
