### ISSUE TITLE
Can't find node by signature spam

### ISSUE THREAD

**Issue by ZacSweers** [Kotlin/dokka#269]
This is a duplicate of #184 but I was asked to make a new issue.

Here is a repro project on 0.9.16-EAP-3 - https://github.com/uber/AutoDispose

and an example of the output data

```
> Task :android:autodispose-android-archcomponents-kotlin:dokka 
warning: duplicate source root: /Users/pandanomic/dev/java/contributing/AutoDispose/android/autodispose-android-archcomponents-kotlin/src/main/kotlin
Can't find node by signature com.uber.autodispose.LifecycleScopeProvider, referenced at com.uber.autodispose.android.lifecycle$scope(android.arch.lifecycle.LifecycleOwner) (autodisposeAndroidLifecycle.kt:28)
Can't find node by signature android.arch.lifecycle.LifecycleOwner, referenced at com.uber.autodispose.android.lifecycle$scope(android.arch.lifecycle.LifecycleOwner) (autodisposeAndroidLifecycle.kt:28)
Can't find node by signature com.uber.autodispose.LifecycleScopeProvider, referenced at com.uber.autodispose.android.lifecycle$scope(android.arch.lifecycle.LifecycleOwner) (autodisposeAndroidLifecycle.kt:28)
Can't find node by signature android.arch.lifecycle.LifecycleOwner, referenced at com.uber.autodispose.android.lifecycle$scope(android.arch.lifecycle.LifecycleOwner) (autodisposeAndroidLifecycle.kt:28)
Can't find node by signature com.uber.autodispose.LifecycleScopeProvider, referenced at com.uber.autodispose.android.lifecycle$scope(android.arch.lifecycle.LifecycleOwner, android.arch.lifecycle.Lifecycle.Event) (autodisposeAndroidLifecycle.kt:34)
Can't find node by signature android.arch.lifecycle.LifecycleOwner, referenced at com.uber.autodispose.android.lifecycle$scope(android.arch.lifecycle.LifecycleOwner, android.arch.lifecycle.Lifecycle.Event) (autodisposeAndroidLifecycle.kt:34)
Can't find node by signature com.uber.autodispose.LifecycleScopeProvider, referenced at com.uber.autodispose.android.lifecycle$scope(android.arch.lifecycle.LifecycleOwner, io.reactivex.functions.Function((android.arch.lifecycle.Lifecycle.Event, ))) (autodisposeAndroidLifecycle.kt:43)
Can't find node by signature android.arch.lifecycle.LifecycleOwner, referenced at com.uber.autodispose.android.lifecycle$scope(android.arch.lifecycle.LifecycleOwner, io.reactivex.functions.Function((android.arch.lifecycle.Lifecycle.Event, ))) (autodisposeAndroidLifecycle.kt:43)
Can't find node by signature com.uber.autodispose.LifecycleScopeProvider, referenced at com.uber.autodispose.android.lifecycle$scope(android.arch.lifecycle.Lifecycle) (autodisposeAndroidLifecycle.kt:52)
Can't find node by signature android.arch.lifecycle.Lifecycle, referenced at com.uber.autodispose.android.lifecycle$scope(android.arch.lifecycle.Lifecycle) (autodisposeAndroidLifecycle.kt:52)
Can't find node by signature com.uber.autodispose.LifecycleScopeProvider, referenced at com.uber.autodispose.android.lifecycle$scope(android.arch.lifecycle.Lifecycle) (autodisposeAndroidLifecycle.kt:52)
Can't find node by signature android.arch.lifecycle.Lifecycle, referenced at com.uber.autodispose.android.lifecycle$scope(android.arch.lifecycle.Lifecycle) (autodisposeAndroidLifecycle.kt:52)
Can't find node by signature com.uber.autodispose.LifecycleScopeProvider, referenced at com.uber.autodispose.android.lifecycle$scope(android.arch.lifecycle.Lifecycle, android.arch.lifecycle.Lifecycle.Event) (autodisposeAndroidLifecycle.kt:58)
Can't find node by signature android.arch.lifecycle.Lifecycle, referenced at com.uber.autodispose.android.lifecycle$scope(android.arch.lifecycle.Lifecycle, android.arch.lifecycle.Lifecycle.Event) (autodisposeAndroidLifecycle.kt:58)
Can't find node by signature com.uber.autodispose.LifecycleScopeProvider, referenced at com.uber.autodispose.android.lifecycle$scope(android.arch.lifecycle.Lifecycle, io.reactivex.functions.Function((android.arch.lifecycle.Lifecycle.Event, ))) (autodisposeAndroidLifecycle.kt:67)
Can't find node by signature android.arch.lifecycle.Lifecycle, referenced at com.uber.autodispose.android.lifecycle$scope(android.arch.lifecycle.Lifecycle, io.reactivex.functions.Function((android.arch.lifecycle.Lifecycle.Event, ))) (autodisposeAndroidLifecycle.kt:67)
Can't find node by signature com.uber.autodispose.LifecycleScopeProvider, referenced at com.uber.autodispose.android.lifecycle$scope(android.arch.lifecycle.Lifecycle) (autodisposeAndroidLifecycle.kt:52)
Can't find node by signature android.arch.lifecycle.Lifecycle, referenced at com.uber.autodispose.android.lifecycle$scope(android.arch.lifecycle.Lifecycle) (autodisposeAndroidLifecycle.kt:52)
Can't find node by signature com.uber.autodispose.LifecycleScopeProvider, referenced at com.uber.autodispose.android.lifecycle$scope(android.arch.lifecycle.Lifecycle) (autodisposeAndroidLifecycle.kt:52)
Can't find node by signature android.arch.lifecycle.Lifecycle, referenced at com.uber.autodispose.android.lifecycle$scope(android.arch.lifecycle.Lifecycle) (autodisposeAndroidLifecycle.kt:52)
Can't find node by signature com.uber.autodispose.LifecycleScopeProvider, referenced at com.uber.autodispose.android.lifecycle$scope(android.arch.lifecycle.Lifecycle, android.arch.lifecycle.Lifecycle.Event) (autodisposeAndroidLifecycle.kt:58)
Can't find node by signature android.arch.lifecycle.Lifecycle, referenced at com.uber.autodispose.android.lifecycle$scope(android.arch.lifecycle.Lifecycle, android.arch.lifecycle.Lifecycle.Event) (autodisposeAndroidLifecycle.kt:58)
Can't find node by signature com.uber.autodispose.LifecycleScopeProvider, referenced at com.uber.autodispose.android.lifecycle$scope(android.arch.lifecycle.Lifecycle, io.reactivex.functions.Function((android.arch.lifecycle.Lifecycle.Event, ))) (autodisposeAndroidLifecycle.kt:67)
Can't find node by signature android.arch.lifecycle.Lifecycle, referenced at com.uber.autodispose.android.lifecycle$scope(android.arch.lifecycle.Lifecycle, io.reactivex.functions.Function((android.arch.lifecycle.Lifecycle.Event, ))) (autodisposeAndroidLifecycle.kt:67)
Can't find node by signature com.uber.autodispose.LifecycleScopeProvider, referenced at com.uber.autodispose.android.lifecycle$scope(android.arch.lifecycle.LifecycleOwner) (autodisposeAndroidLifecycle.kt:28)
Can't find node by signature android.arch.lifecycle.LifecycleOwner, referenced at com.uber.autodispose.android.lifecycle$scope(android.arch.lifecycle.LifecycleOwner) (autodisposeAndroidLifecycle.kt:28)
Can't find node by signature com.uber.autodispose.LifecycleScopeProvider, referenced at com.uber.autodispose.android.lifecycle$scope(android.arch.lifecycle.LifecycleOwner) (autodisposeAndroidLifecycle.kt:28)
Can't find node by signature android.arch.lifecycle.LifecycleOwner, referenced at com.uber.autodispose.android.lifecycle$scope(android.arch.lifecycle.LifecycleOwner) (autodisposeAndroidLifecycle.kt:28)
Can't find node by signature com.uber.autodispose.LifecycleScopeProvider, referenced at com.uber.autodispose.android.lifecycle$scope(android.arch.lifecycle.LifecycleOwner, android.arch.lifecycle.Lifecycle.Event) (autodisposeAndroidLifecycle.kt:34)
Can't find node by signature android.arch.lifecycle.LifecycleOwner, referenced at com.uber.autodispose.android.lifecycle$scope(android.arch.lifecycle.LifecycleOwner, android.arch.lifecycle.Lifecycle.Event) (autodisposeAndroidLifecycle.kt:34)
Can't find node by signature com.uber.autodispose.LifecycleScopeProvider, referenced at com.uber.autodispose.android.lifecycle$scope(android.arch.lifecycle.LifecycleOwner, io.reactivex.functions.Function((android.arch.lifecycle.Lifecycle.Event, ))) (autodisposeAndroidLifecycle.kt:43)
Can't find node by signature android.arch.lifecycle.LifecycleOwner, referenced at com.uber.autodispose.android.lifecycle$scope(android.arch.lifecycle.LifecycleOwner, io.reactivex.functions.Function((android.arch.lifecycle.Lifecycle.Event, ))) (autodisposeAndroidLifecycle.kt:43)
```

**Comment by arturbosch** [comment]
We are seeing similar warnings at detekt:
```
null:-1:-1: Tag @see cannot be used in inline documentation.  It can only be used in the following types of documentation: overview, package, class/interface, constructor, field, method.
Can't find node by signature not implemented for deserialized class KtFile with psi: null, referenced at io.gitlab.arturbosch.detekt.api.RuleSet$accept(org.jetbrains.kotlin.psi.KtFile, kotlin
```

**Comment by semoro** [comment]
@arturbosch Please, create new issue about that

**Comment by kirill-grouchnikov** [comment]
Seeing the same issue with my multi-project setup. Project B is in Kotlin and references APIs from project A which is in Java. All these references are marked as "Can't find node by signature" running B:dokka task.

**Comment by kamilok1965** [comment]
It's a problem with cross-project references, the same as https://github.com/Kotlin/dokka/issues/284. It'll be fixed in the upcoming 0.9.18 release. 
You'll have to configure your modules like that: 
```
evaluationDependsOn(":autodispose")
afterEvaluate {
  dokka {
    classpath = configurations.compile
    externalDocumentationLink {
      packageListUrl = new URL("file://${project(":autodispose").buildDir}/dokka/autodispose/package-list")
      url = new URL("file://${project(":autodispose").buildDir}/dokka/autodispose/")
    }
  }
}
```

**Comment by kirill-grouchnikov** [comment]
Is this a temporary workaround for 0.9.17, or will that be required even with the upcoming fix in 0.9.18?

**Comment by kamilok1965** [comment]
It doesn't work on 0.9.17, it's a preferred way for resolving cross-project references on 0.9.18

**Comment by kirill-grouchnikov** [comment]
Just to clarify - when 0.9.18 rolls out, any Kotlin project that references any Java classes in its inline documentation would have to add that snippet to their build script?

**Comment by kamilok1965** [comment]
Not exactly. Any Project that uses Dokka and references another project in its documentation will have to add that snippet to the build script. It doesn't matter whether it links to Java or Kotlin classes.  

For example in the AutoDispose project there is a Gradle subproject called `autodispose-ktx` which references functions from another Gradle subproject `autodispose`. Each of the subprojects have their own Dokka plugins which generate separate documentations. With the aforementioned snippet you can make the plugins aware of another projects, so the links can be resolved correctly. So in this case adding the configuration to the `build.gradle` file inside the `autodispose-ktx` project solves the problem

**Comment by ZacSweers** [comment]
The above example isn't quite going to work, because the `autodispose` subproject is just a plain java project with no dokka applied. Is the implication that even pure java projects should also apply the dokka plugin?

**Comment by ZacSweers** [comment]
Just to be clear - it definitely doesn't work with the current example anyway, since it expects a dokka file in the common autodispose module that's not going to exist without the dokka plugin running

```
> Guice provision errors:
  
  1) Error injecting constructor, java.lang.RuntimeException: Exception while loading package-list from ExternalDocumentationLinkImpl(url=file:/Users/zsweers/dev/uber/AutoDispose/autodispose/build/dokka/autodispose/, packageListUrl=file:/Users/zsweers/dev/uber/AutoDispose/autodispose/build/dokka/autodispose/package-list)
    at org.jetbrains.dokka.ExternalDocumentationLinkResolver.<init>(ExternalDocumentationLinkResolver.kt:32)
    at org.jetbrains.dokka.ExternalDocumentationLinkResolver.class(ExternalDocumentationLinkResolver.kt:32)
    while locating org.jetbrains.dokka.ExternalDocumentationLinkResolver
      for parameter 4 at org.jetbrains.dokka.DeclarationLinkResolver.<init>(DeclarationLinkResolver.kt:10)
    while locating org.jetbrains.dokka.DeclarationLinkResolver
      for parameter 0 at org.jetbrains.dokka.PackageDocs.<init>(PackageDocs.kt:20)
    at org.jetbrains.dokka.PackageDocs.class(PackageDocs.kt:19)
    while locating org.jetbrains.dokka.PackageDocs
  
  1 error

```

**Comment by semoro** [comment]
If it is Javadoc, you should provide a path to Javadoc's `package-list`, no need to apply Dokka to that project. However, if you using JavaDoc from JDK 9+ it might generate module-list, which is not supported by Dokka now, so you'll need to manually provide `package-list` file
