### ISSUE TITLE
Dokka fails to generate docs when javadocs contains smth like "[<anything>]"

### ISSUE THREAD

**Issue by jay-from-future** [Kotlin/dokka#2726]
**Describe the bug**
Dokka fails to generate docs when javadocs contains smth like "[<anything>]"

**Expected behaviour**
Dokka generates docs (or provide more clear error message why it is not possible)

**Screenshots**
![image](https://user-images.githubusercontent.com/5632433/197180970-b4072ed1-5b07-47a6-9f11-a9384bd68ffa.png)

**To Reproduce**
1. Project https://github.com/jay-from-future/dokka-check
2. Run gralde task **dokkaHtml**

**Dokka configuration**
Pretty standard configuration, just added "id("org.jetbrains.dokka") version "1.7.20"" to plugins section in build.gradle.kts

**Installation**
- Operating system: Windows
- Build tool: Gradle v7.5.1
- Dokka version: 1.7.20

**Comment by IgnatBeresnev** [comment]
Not that it makes much difference to the user, but it's not Dokka that fails, but the compiler:

```kotlin
/**
 * Testing [<asd>]
 */
class Foo {}
```

```
Caused by: java.lang.IllegalStateException: not identifier: <asd>
        at org.jetbrains.kotlin.name.Name.getIdentifier(Name.java:40)
        at org.jetbrains.kotlin.cli.jvm.index.JvmDependenciesIndexImpl.search(JvmDependenciesIndexImpl.kt:114)
        at org.jetbrains.kotlin.cli.jvm.index.JvmDependenciesIndexImpl.traverseDirectoriesInPackage(JvmDependenciesIndexImpl.kt:76)
        at org.jetbrains.kotlin.cli.jvm.index.JvmDependenciesDynamicCompoundIndex.traverseDirectoriesInPackage(JvmDependenciesDynamicCompoundIndex.kt:59)
        at org.jetbrains.kotlin.cli.jvm.index.JvmDependenciesIndex$DefaultImpls.traverseDirectoriesInPackage$default(JvmDependenciesIndex.kt:35)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCliJavaFileManagerImpl.findPackage(KotlinCliJavaFileManagerImpl.kt:195)
        at org.jetbrains.kotlin.resolve.jvm.KotlinJavaPsiFacade$CliFinder.findPackage(KotlinJavaPsiFacade.java:502)
        at org.jetbrains.kotlin.resolve.jvm.KotlinJavaPsiFacade.findPackage(KotlinJavaPsiFacade.java:346)
        at org.jetbrains.kotlin.load.java.JavaClassFinderImpl.findPackage(JavaClassFinderImpl.kt:48)
        at org.jetbrains.kotlin.load.java.JavaClassFinder$DefaultImpls.findPackage$default(JavaClassFinder.kt:24)
        at org.jetbrains.kotlin.load.java.lazy.LazyJavaPackageFragmentProvider.isEmpty(LazyJavaPackageFragmentProvider.kt:51)
        at org.jetbrains.kotlin.descriptors.PackageFragmentProviderKt.isEmpty(PackageFragmentProvider.kt:49)
        at org.jetbrains.kotlin.descriptors.impl.CompositePackageFragmentProvider.isEmpty(CompositePackageFragmentProvider.kt:51)
        at org.jetbrains.kotlin.descriptors.PackageFragmentProviderKt.isEmpty(PackageFragmentProvider.kt:49)
        at org.jetbrains.kotlin.analyzer.DelegatingPackageFragmentProvider.isEmpty(AbstractResolverForProject.kt:261)
        at org.jetbrains.kotlin.descriptors.PackageFragmentProviderKt.isEmpty(PackageFragmentProvider.kt:49)
        at org.jetbrains.kotlin.descriptors.impl.CompositePackageFragmentProvider.isEmpty(CompositePackageFragmentProvider.kt:51)
        at org.jetbrains.kotlin.descriptors.PackageFragmentProviderKt.isEmpty(PackageFragmentProvider.kt:49)
        at org.jetbrains.kotlin.descriptors.impl.LazyPackageViewDescriptorImpl$empty$2.invoke(LazyPackageViewDescriptorImpl.kt:39)
        at org.jetbrains.kotlin.descriptors.impl.LazyPackageViewDescriptorImpl$empty$2.invoke(LazyPackageViewDescriptorImpl.kt:38)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedLazyValue.invoke(LockBasedStorageManager.java:408)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedNotNullLazyValue.invoke(LockBasedStorageManager.java:527)
        at org.jetbrains.kotlin.storage.StorageKt.getValue(storage.kt:42)
        at org.jetbrains.kotlin.descriptors.impl.LazyPackageViewDescriptorImpl.getEmpty(LazyPackageViewDescriptorImpl.kt:38)
        at org.jetbrains.kotlin.descriptors.impl.LazyPackageViewDescriptorImpl.isEmpty(LazyPackageViewDescriptorImpl.kt:42)
        at org.jetbrains.kotlin.descriptors.impl.SubpackagesScope.getPackage(SubpackagesScope.kt:38)
        at org.jetbrains.kotlin.resolve.scopes.SubpackagesImportingScope.getContributedPackage(SubpackagesImportingScope.kt:35)
        at org.jetbrains.kotlin.resolve.scopes.utils.ScopeUtilsKt.findPackage(ScopeUtils.kt:122)
        at org.jetbrains.kotlin.idea.kdoc.ResolveKDocLinkKt.resolveLocal(resolveKDocLink.kt:101)
        at org.jetbrains.kotlin.idea.kdoc.ResolveKDocLinkKt.resolveKDocLink(resolveKDocLink.kt:48)
        at org.jetbrains.dokka.base.translators.descriptors.DokkaDescriptorVisitor$getDocumentation$$inlined$let$lambda$1.invoke(DefaultDescriptorToDocumentableTranslator.kt:1024)
        at org.jetbrains.dokka.base.translators.descriptors.DokkaDescriptorVisitor$getDocumentation$$inlined$let$lambda$1.invoke(DefaultDescriptorToDocumentableTranslator.kt:133)
        at org.jetbrains.dokka.base.parsers.MarkdownParser.resolveDRI(MarkdownParser.kt:158)
        at org.jetbrains.dokka.base.parsers.MarkdownParser.linksHandler(MarkdownParser.kt:211)
        at org.jetbrains.dokka.base.parsers.MarkdownParser.linksHandler$default(MarkdownParser.kt:210)
        at org.jetbrains.dokka.base.parsers.MarkdownParser.referenceLinksHandler(MarkdownParser.kt:181)
        at org.jetbrains.dokka.base.parsers.MarkdownParser.visitNode(MarkdownParser.kt:372)
        at org.jetbrains.dokka.base.parsers.MarkdownParser.evaluateChildren(MarkdownParser.kt:408)
        at org.jetbrains.dokka.base.parsers.MarkdownParser.evaluateChildren$default(MarkdownParser.kt:407)
        at org.jetbrains.dokka.base.parsers.MarkdownParser.defaultHandler(MarkdownParser.kt:355)
        at org.jetbrains.dokka.base.parsers.MarkdownParser.visitNode(MarkdownParser.kt:398)
        at org.jetbrains.dokka.base.parsers.MarkdownParser.evaluateChildren(MarkdownParser.kt:408)
        at org.jetbrains.dokka.base.parsers.MarkdownParser.evaluateChildren$default(MarkdownParser.kt:407)
        at org.jetbrains.dokka.base.parsers.MarkdownParser.markdownFileHandler(MarkdownParser.kt:201)
        at org.jetbrains.dokka.base.parsers.MarkdownParser.visitNode(MarkdownParser.kt:392)
        at org.jetbrains.dokka.base.parsers.MarkdownParser.visitNode$default(MarkdownParser.kt:358)
        at org.jetbrains.dokka.base.parsers.MarkdownParser.parseStringToDocNode(MarkdownParser.kt:40)
        at org.jetbrains.dokka.base.parsers.MarkdownParser$Companion$parseFromKDocTag$1.invoke(MarkdownParser.kt:514)
        at org.jetbrains.dokka.base.parsers.MarkdownParser$Companion.parseFromKDocTag(MarkdownParser.kt:526)
        at org.jetbrains.dokka.base.parsers.MarkdownParser$Companion.parseFromKDocTag$default(MarkdownParser.kt:508)
        at org.jetbrains.dokka.base.translators.descriptors.DokkaDescriptorVisitor.getDocumentation(DefaultDescriptorToDocumentableTranslator.kt:1020)
        at org.jetbrains.dokka.base.translators.descriptors.DokkaDescriptorVisitor.resolveDescriptorData(DefaultDescriptorToDocumentableTranslator.kt:901)
        at org.jetbrains.dokka.base.translators.descriptors.DokkaDescriptorVisitor.access$resolveDescriptorData(DefaultDescriptorToDocumentableTranslator.kt:133)
        at org.jetbrains.dokka.base.translators.descriptors.DokkaDescriptorVisitor$resolveClassDescriptionData$2.invokeSuspend(DefaultDescriptorToDocumentableTranslator.kt:936)
        at org.jetbrains.dokka.base.translators.descriptors.DokkaDescriptorVisitor$resolveClassDescriptionData$2.invoke(DefaultDescriptorToDocumentableTranslator.kt)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
        at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)
        at org.jetbrains.dokka.base.translators.descriptors.DokkaDescriptorVisitor.resolveClassDescriptionData(DefaultDescriptorToDocumentableTranslator.kt:933)
        at org.jetbrains.dokka.base.translators.descriptors.DokkaDescriptorVisitor.classDescriptor(DefaultDescriptorToDocumentableTranslator.kt:390)
        at org.jetbrains.dokka.base.translators.descriptors.DokkaDescriptorVisitor.visitClassDescriptor(DefaultDescriptorToDocumentableTranslator.kt:181)
        at org.jetbrains.dokka.base.translators.descriptors.DokkaDescriptorVisitor$visitClasslikes$2$invokeSuspend$$inlined$parallelMap$1$1.invokeSuspend(parallelCollectionOperations.kt:17)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

```
