### ISSUE TITLE
Failed to enable K2 analyses with DocumentableSourceLanguageParser not present

### ISSUE THREAD

**Issue by atyrin** [Kotlin/dokka#3331]
Add the flag `org.jetbrains.dokka.experimental.tryK2=true` to gradle.properties.

The dokkaHtml task failing with

```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':dokkaHtml'.
Caused by: java.lang.TypeNotPresentException: Type org.jetbrains.dokka.analysis.kotlin.internal.DocumentableSourceLanguageParser not present
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.<init>(CallerImpl.kt:90)
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.<init>(CallerImpl.kt)
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.<init>(CallerImpl.kt:84)
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.<init>(CallerImpl.kt:110)
	at kotlin.reflect.jvm.internal.KPropertyImplKt.computeCallerForAccessor(KPropertyImpl.kt:287)
	at kotlin.reflect.jvm.internal.KPropertyImplKt.access$computeCallerForAccessor(KPropertyImpl.kt:1)
	at kotlin.reflect.jvm.internal.KPropertyImpl$Getter$caller$2.invoke(KPropertyImpl.kt:180)
	at kotlin.reflect.jvm.internal.KPropertyImpl$Getter$caller$2.invoke(KPropertyImpl.kt:179)
	at kotlin.SafePublicationLazyImpl.getValue(LazyJVM.kt:107)
	at kotlin.reflect.jvm.internal.KPropertyImpl$Getter.getCaller(KPropertyImpl.kt:179)
	at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108)
	at kotlin.reflect.jvm.internal.KProperty1Impl.get(KProperty1Impl.kt:35)
	at org.jetbrains.dokka.plugability.DokkaPlugin$internalInstall$extensionsToInstall$1.invoke(DokkaPlugin.kt:78)
	at org.jetbrains.dokka.plugability.DokkaPlugin$internalInstall$extensionsToInstall$1.invoke(DokkaPlugin.kt:78)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
	at kotlin.sequences.FlatteningSequence$iterator$1.next(Sequences.kt:299)
	at org.jetbrains.dokka.plugability.DokkaPlugin.internalInstall$dokka_core(DokkaPlugin.kt:121)
	at org.jetbrains.dokka.plugability.DokkaContextConfigurationImpl.install(DokkaContext.kt:179)
	at org.jetbrains.dokka.plugability.DokkaContext$Companion.create(DokkaContext.kt:41)
	at org.jetbrains.dokka.DokkaGenerator.initializePlugins(DokkaGenerator.kt:49)
	at org.jetbrains.dokka.DokkaGenerator.initializePlugins$default(DokkaGenerator.kt:45)
	at org.jetbrains.dokka.DokkaGenerator$generate$1.invoke(DokkaGenerator.kt:29)
	at org.jetbrains.dokka.DokkaGenerator$generate$1.invoke(DokkaGenerator.kt:27)
	at org.jetbrains.dokka.DokkaGeneratorKt.timed(DokkaGenerator.kt:82)
	at org.jetbrains.dokka.DokkaGeneratorKt.access$timed(DokkaGenerator.kt:1)
	at org.jetbrains.dokka.DokkaGenerator.generate(DokkaGenerator.kt:27)
	at org.jetbrains.dokka.DokkaBootstrapImpl.generate(DokkaBootstrapImpl.kt:67)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.jetbrains.dokka.gradle.DelegatedInvocationHandler.invoke(automagicTypedProxy.kt:44)
	at jdk.proxy4/jdk.proxy4.$Proxy111.generate(Unknown Source)
	at org.jetbrains.dokka.gradle.AbstractDokkaTask$generateDocumentation$1$1.run(AbstractDokkaTask.kt:217)
Caused by: java.lang.ClassNotFoundException: org.jetbrains.dokka.analysis.kotlin.internal.DocumentableSourceLanguageParser
	... 33 more
```

Dokka: 1.9.20
#3328

**Comment by whyoleg** [comment]
most likely the reason is: https://github.com/Kotlin/dokka/pull/3152#discussion_r1388212869

**Comment by IgnatBeresnev** [comment]
@atyrin can you please try again with latest master? #3333 was merged in a minute ago and it might help (thanks to @whyoleg for pointing it out)

**Comment by atyrin** [comment]
@IgnatBeresnev thanks. That helped.
