### ISSUE TITLE
[K2] Typealias to functional type with reciever leads to IndexOutOfBoundsException

### ISSUE THREAD

**Issue by atyrin** [Kotlin/dokka#3392]
The code
```Kotlin
typealias HttpExceptionCallback<T> = String.(T) -> String

fun <T> exception(
    callback: HttpExceptionCallback<T>,
){}
```
leads to a failure:
```
Caused by: java.lang.IndexOutOfBoundsException: fromIndex: 0, toIndex: -1
	at kotlin.collections.EmptyList.subList(Collections.kt:50)
	at org.jetbrains.dokka.base.signatures.KotlinSignatureProvider$funType$1.invoke(KotlinSignatureProvider.kt:486)
	at org.jetbrains.dokka.base.signatures.KotlinSignatureProvider$funType$1.invoke(KotlinSignatureProvider.kt:466)
	at org.jetbrains.dokka.base.translators.documentables.PageContentBuilder.contentFor(PageContentBuilder.kt:38)
	at org.jetbrains.dokka.base.translators.documentables.PageContentBuilder.contentFor$default(PageContentBuilder.kt:29)
	at org.jetbrains.dokka.base.signatures.KotlinSignatureProvider.funType(KotlinSignatureProvider.kt:466)
	at org.jetbrains.dokka.base.signatures.KotlinSignatureProvider.signatureForProjection(KotlinSignatureProvider.kt:417)
	at org.jetbrains.dokka.base.signatures.KotlinSignatureProvider.signatureForProjection$default(KotlinSignatureProvider.kt:405)
	at org.jetbrains.dokka.base.signatures.KotlinSignatureProvider$functionSignature$1$1$10.invoke(KotlinSignatureProvider.kt:331)
	at org.jetbrains.dokka.base.signatures.KotlinSignatureProvider$functionSignature$1$1$10.invoke(KotlinSignatureProvider.kt:326)
	at org.jetbrains.dokka.base.signatures.JvmSignatureUtils$parametersBlock$1$2.invoke(JvmSignatureUtils.kt:222)
	at org.jetbrains.dokka.base.signatures.JvmSignatureUtils$parametersBlock$1$2.invoke(JvmSignatureUtils.kt:221)
	at org.jetbrains.dokka.base.translators.documentables.PageContentBuilder.contentFor(PageContentBuilder.kt:50)
	at org.jetbrains.dokka.base.translators.documentables.PageContentBuilder$DocumentableContentBuilder.buildGroup(PageContentBuilder.kt:522)
	at org.jetbrains.dokka.base.translators.documentables.PageContentBuilder$DocumentableContentBuilder.group(PageContentBuilder.kt:497)
	at org.jetbrains.dokka.base.translators.documentables.PageContentBuilder$DocumentableContentBuilder.group$default(PageContentBuilder.kt:489)
	at org.jetbrains.dokka.base.signatures.JvmSignatureUtils$parametersBlock$1.invoke(JvmSignatureUtils.kt:221)
	at org.jetbrains.dokka.base.signatures.JvmSignatureUtils$parametersBlock$1.invoke(JvmSignatureUtils.kt:214)
	at org.jetbrains.dokka.base.translators.documentables.PageContentBuilder.contentFor(PageContentBuilder.kt:50)
	at org.jetbrains.dokka.base.translators.documentables.PageContentBuilder$DocumentableContentBuilder.buildGroup(PageContentBuilder.kt:522)
	at org.jetbrains.dokka.base.translators.documentables.PageContentBuilder$DocumentableContentBuilder.group(PageContentBuilder.kt:497)
	at org.jetbrains.dokka.base.translators.documentables.PageContentBuilder$DocumentableContentBuilder.group$default(PageContentBuilder.kt:489)
	at org.jetbrains.dokka.base.signatures.JvmSignatureUtils$DefaultImpls.parametersBlock(JvmSignatureUtils.kt:214)
	at org.jetbrains.dokka.base.signatures.KotlinSignatureUtils.parametersBlock(KotlinSignatureUtils.kt:18)
	at org.jetbrains.dokka.base.signatures.KotlinSignatureProvider.parametersBlock(KotlinSignatureProvider.kt)
	at org.jetbrains.dokka.base.signatures.KotlinSignatureProvider$functionSignature$1$1.invoke(KotlinSignatureProvider.kt:326)
	at org.jetbrains.dokka.base.signatures.KotlinSignatureProvider$functionSignature$1$1.invoke(KotlinSignatureProvider.kt:291)
	at org.jetbrains.dokka.base.translators.documentables.PageContentBuilder.contentFor(PageContentBuilder.kt:62)
	at org.jetbrains.dokka.base.translators.documentables.PageContentBuilder.contentFor$default(PageContentBuilder.kt:53)
	at org.jetbrains.dokka.base.signatures.KotlinSignatureProvider.functionSignature(KotlinSignatureProvider.kt:291)
	at org.jetbrains.dokka.base.signatures.KotlinSignatureProvider.signature(KotlinSignatureProvider.kt:49)
	at org.jetbrains.dokka.base.translators.documentables.PageContentBuilder$DocumentableContentBuilder.buildSignature(PageContentBuilder.kt:169)
	at org.jetbrains.dokka.base.translators.documentables.DefaultPageCreator$contentForMembers$1$2$1$1$1.invoke(DefaultPageCreator.kt:636)
	at org.jetbrains.dokka.base.translators.documentables.DefaultPageCreator$contentForMembers$1$2$1$1$1.invoke(DefaultPageCreator.kt:635)
	at org.jetbrains.dokka.base.translators.documentables.PageContentBuilder.contentFor(PageContentBuilder.kt:50)
	at org.jetbrains.dokka.base.translators.documentables.PageContentBuilder$DivergentInstanceBuilder.divergent(PageContentBuilder.kt:710)
	at org.jetbrains.dokka.base.translators.documentables.PageContentBuilder$DivergentInstanceBuilder.divergent$default(PageContentBuilder.kt:702)
	at org.jetbrains.dokka.base.translators.documentables.DefaultPageCreator$contentForMembers$1$2$1$1.invoke(DefaultPageCreator.kt:635)
	at org.jetbrains.dokka.base.translators.documentables.DefaultPageCreator$contentForMembers$1$2$1$1.invoke(DefaultPageCreator.kt:634)
	at org.jetbrains.dokka.base.translators.documentables.PageContentBuilder$DivergentBuilder.instance(PageContentBuilder.kt:656)
	at org.jetbrains.dokka.base.translators.documentables.PageContentBuilder$DivergentBuilder.instance$default(PageContentBuilder.kt:647)
	at org.jetbrains.dokka.base.translators.documentables.DefaultPageCreator$contentForMembers$1$2.invoke(DefaultPageCreator.kt:634)
	at org.jetbrains.dokka.base.translators.documentables.DefaultPageCreator$contentForMembers$1$2.invoke(DefaultPageCreator.kt:632)
	at org.jetbrains.dokka.base.translators.documentables.PageContentBuilder$DocumentableContentBuilder.divergentGroup(PageContentBuilder.kt:511)
	at org.jetbrains.dokka.base.translators.documentables.PageContentBuilder$DocumentableContentBuilder.divergentGroup$default(PageContentBuilder.kt:500)
	at org.jetbrains.dokka.base.translators.documentables.DefaultPageCreator$contentForMembers$1.invoke(DefaultPageCreator.kt:632)
	at org.jetbrains.dokka.base.translators.documentables.DefaultPageCreator$contentForMembers$1.invoke(DefaultPageCreator.kt:628)
	at org.jetbrains.dokka.base.translators.documentables.PageContentBuilder.contentFor(PageContentBuilder.kt:50)
	at org.jetbrains.dokka.base.translators.documentables.PageContentBuilder.contentFor$default(PageContentBuilder.kt:41)
	at org.jetbrains.dokka.base.translators.documentables.DefaultPageCreator.contentForMembers(DefaultPageCreator.kt:628)
	at org.jetbrains.dokka.base.translators.documentables.DefaultPageCreator.contentForMember(DefaultPageCreator.kt:625)
	at org.jetbrains.dokka.base.translators.documentables.DefaultPageCreator.contentForFunction(DefaultPageCreator.kt:621)
	at org.jetbrains.dokka.base.translators.documentables.DefaultPageCreator.pageForFunction(DefaultPageCreator.kt:198)
	at org.jetbrains.dokka.base.translators.documentables.DefaultPageCreator.pageForClasslikes(DefaultPageCreator.kt:160)
	at org.jetbrains.dokka.base.translators.documentables.DefaultPageCreator.pageForClasslike(DefaultPageCreator.kt:101)
	at org.jetbrains.dokka.base.translators.documentables.DefaultPageCreator.pageForPackage(DefaultPageCreator.kt:86)
	at org.jetbrains.dokka.base.translators.documentables.DefaultPageCreator.pageForModule(DefaultPageCreator.kt:55)
	at org.jetbrains.dokka.base.translators.documentables.DefaultDocumentableToPageTranslator.invoke(DefaultDocumentableToPageTranslator.kt:33)
	at org.jetbrains.dokka.base.translators.documentables.DefaultDocumentableToPageTranslator.invoke(DefaultDocumentableToPageTranslator.kt:15)
	at org.jetbrains.dokka.base.generation.SingleModuleGeneration.createPages(SingleModuleGeneration.kt:88)
	at org.jetbrains.dokka.base.generation.SingleModuleGeneration.generate(SingleModuleGeneration.kt:46)
```

Works with K1.

**Installation**
- Dokka version: 1.9.20

Parent: https://github.com/Kotlin/dokka/issues/3328

**Comment by atyrin** [comment]
Affects ktor and Hexagon projects.
