### ISSUE TITLE
Theme switcher doesn't work on the root page of multimodule project

### ISSUE THREAD

**Issue by atyrin** [Kotlin/dokka#3616]
After fix of #3596 the theme switcher doesn't work on the root page for a multimodule project
browser console error"
```
Uncaught TypeError: KotlinPlayground is not a function
    at initPlayground (platform-content-handler.js:66:5)
    at darkModeSwitch (platform-content-handler.js:39:5)
    at platform-content-handler.js:30:5
```

Works on other pages.

**Installation**
- Dokka version: 2.0.0

**Comment by atyrin** [comment]
Fixed in 2.0
