### ISSUE TITLE
GradleDokkaSourceSetBuilder uses deprecated org.gradle.util.ConfigureUtil

### ISSUE THREAD

**Issue by snicoll** [Kotlin/dokka#3707]
**Describe the bug**
If you run the plugin with a recent Gradle version it outputs the following:

```
The org.gradle.util.ConfigureUtil type has been deprecated. This is scheduled to be removed in Gradle 9.0. Consult the upgrading guide for further information: https://docs.gradle.org/8.9/userguide/upgrading_version_8.html#org_gradle_util_reports_deprecations
        at org.gradle.util.ConfigureUtil.logDeprecation(ConfigureUtil.java:215)
        at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:148)
        at org.jetbrains.dokka.gradle.GradleDokkaSourceSetBuilder.externalDocumentationLink(GradleDokkaSourceSetBuilder.kt:442)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at docs_dokka_3riv5nslbmzek8bjm6sn0yln1$_run_closure1$_closure2$_closure3.doCall$original(/Users/snicoll/workspace/work/spring-framework/6.1.x/gradle/docs-dokka.gradle:7)
        at docs_dokka_3riv5nslbmzek8bjm6sn0yln1$_run_closure1$_closure2$_closure3.doCall(/Users/snicoll/workspace/work/spring-framework/6.1.x/gradle/docs-dokka.gradle)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1030)
        at groovy.lang.Closure.call(Closure.java:427)
        at groovy.lang.Closure.call(Closure.java:416)
        at org.gradle.util.internal.ClosureBackedAction.execute(ClosureBackedAction.java:73)
        at org.gradle.util.internal.ConfigureUtil.configureTarget(ConfigureUtil.java:166)
        at org.gradle.util.internal.ConfigureUtil.configure(ConfigureUtil.java:107)
        at org.gradle.util.internal.ConfigureUtil$WrappedConfigureAction.execute(ConfigureUtil.java:178)
        at org.gradle.internal.code.DefaultUserCodeApplicationContext$CurrentApplication$1.execute(DefaultUserCodeApplicationContext.java:124)
        at org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction$1.run(DefaultCollectionCallbackActionDecorator.java:110)
```

This can be reproduced by configuring external links on the task.

**Expected behaviour**
Plugin should not use deprecated feature so that users can prepare the upgrade to Gradle 9

**Screenshots**

**To Reproduce**
Run`./gradlew dokkaHtmlPartial --warning-mode all --stacktrace` on the [Spring Framework project](https://github.com/spring-projects/spring-framework/)

**Dokka configuration**
Configuration of dokka used to reproduce the bug: https://github.com/spring-projects/spring-framework/blob/7c9bb2429631407b97647e2bda3036b55b0bbf2b/gradle/docs-dokka.gradle

**Installation**
- Operating system: macOS
- Build tool: Gradle v8.9
- Dokka version: 1.8.20

**Additional context**

**Comment by whyoleg** [comment]
Should be not an issue in [Dokka 2.0.0](https://github.com/Kotlin/dokka/releases/tag/v2.0.0) in [Dokka Gradle plugin v2﻿](https://kotlinlang.org/docs/dokka-migration.html)
