### ISSUE TITLE
Generation fails for expect declared in intermediate source set

### ISSUE THREAD

**Issue by atyrin** [Kotlin/dokka#3798]
Create a KMP project with jvm + linuxX64 + macosX64. And such code in source sets:
```Kotlin
// nativeMain
expect fun shared()

// linuxX64Main, macosX64Main
actual fun shared(){}
```

```
Caused by: java.lang.IllegalArgumentException: Collection has more than one element.
	at kotlin.collections.CollectionsKt___CollectionsKt.single(_Collections.kt:605)
	at org.jetbrains.dokka.transformers.documentation.DefaultDocumentableMerger.mergeExpectActual$analyzeExpectActual(DefaultDocumentableMerger.kt:119)
	at org.jetbrains.dokka.transformers.documentation.DefaultDocumentableMerger.mergeExpectActual(DefaultDocumentableMerger.kt:136)
	at org.jetbrains.dokka.transformers.documentation.DefaultDocumentableMerger.mergeWith(DefaultDocumentableMerger.kt:141)
	at org.jetbrains.dokka.transformers.documentation.DefaultDocumentableMerger$invoke$1$3.invoke(DefaultDocumentableMerger.kt:35)
	at org.jetbrains.dokka.transformers.documentation.DefaultDocumentableMerger$invoke$1$3.invoke(DefaultDocumentableMerger.kt:33)
	at org.jetbrains.dokka.transformers.documentation.DefaultDocumentableMerger.merge(DefaultDocumentableMerger.kt:55)
	at org.jetbrains.dokka.transformers.documentation.DefaultDocumentableMerger.invoke(DefaultDocumentableMerger.kt:33)
	at org.jetbrains.dokka.base.generation.SingleModuleGeneration.mergeDocumentationModels(SingleModuleGeneration.kt:82)
	at org.jetbrains.dokka.base.generation.SingleModuleGeneration.generate(SingleModuleGeneration.kt:38)
	at org.jetbrains.dokka.DokkaGenerator$generate$1.invoke(DokkaGenerator.kt:34)
	at org.jetbrains.dokka.DokkaGenerator$generate$1.invoke(DokkaGenerator.kt:27)
	at org.jetbrains.dokka.DokkaGeneratorKt.timed(DokkaGenerator.kt:82)
	at org.jetbrains.dokka.DokkaGeneratorKt.access$timed(DokkaGenerator.kt:1)
	at org.jetbrains.dokka.DokkaGenerator.generate(DokkaGenerator.kt:27)
	at org.jetbrains.dokka.DokkaBootstrapImpl.generate(DokkaBootstrapImpl.kt:67)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.jetbrains.dokka.gradle.DelegatedInvocationHandler.invoke(automagicTypedProxy.kt:44)
	at jdk.proxy4/jdk.proxy4.$Proxy127.generate(Unknown Source)
	at org.jetbrains.dokka.gradle.AbstractDokkaTask$generateDocumentation$1$1.run(AbstractDokkaTask.kt:232)
```

**Installation**
- Dokka version: 2.0.20-dev-357
- DGPv1 / K1 or K2

[dokka-repros.zip](https://github.com/user-attachments/files/16966581/dokka-repros.zip)

**Comment by whyoleg** [comment]
Most likely caused by the changes in https://github.com/Kotlin/dokka/pull/3662

**Comment by ZacSweers** [comment]
Here is a repro case: https://github.com/slackhq/circuit/pull/1732
