### ISSUE TITLE
404 when building docs with jdkVersion >9

### ISSUE THREAD

**Issue by josephlbarnett** [Kotlin/dokka#416]
Trying to use dokka with jdkVersion > 9 results in 404 errors.  It looks like the jdk11 api path has changed from http://docs.oracle.com/javase/${jdkVersion}/docs/api/ to https://docs.oracle.com/en/java/javase/${jdkVersion}/docs/api/, and that neither jdk10 nor jdk11 are providing `package-list`s?

jdk 10:
```
[ERROR] Failed to execute goal org.jetbrains.dokka:dokka-maven-plugin:0.9.17:dokka (default) on project config: Execution default of goal org.jetbrains.dokka:dokka-maven-plugin:0.9.17:dokka failed: Guice provision errors:
[ERROR] 
[ERROR] 1) Error injecting constructor, java.lang.RuntimeException: Exception while loading package-list from ExternalDocumentationLinkImpl(url=http://docs.oracle.com/javase/10/docs/api/, packageListUrl=http://docs.oracle.com/javase/10/docs/api/package-list)
[ERROR]   at org.jetbrains.dokka.ExternalDocumentationLinkResolver.<init>(ExternalDocumentationLinkResolver.kt:28)
[ERROR]   at org.jetbrains.dokka.ExternalDocumentationLinkResolver.class(ExternalDocumentationLinkResolver.kt:28)
[ERROR]   while locating org.jetbrains.dokka.ExternalDocumentationLinkResolver
[ERROR]     for parameter 4 at org.jetbrains.dokka.DeclarationLinkResolver.<init>(DeclarationLinkResolver.kt:13)
[ERROR]   while locating org.jetbrains.dokka.DeclarationLinkResolver
[ERROR]     for parameter 0 at org.jetbrains.dokka.PackageDocs.<init>(PackageDocs.kt:13)
[ERROR]   at org.jetbrains.dokka.PackageDocs.class(PackageDocs.kt:12)
[ERROR]   while locating org.jetbrains.dokka.PackageDocs
```

jdk11:
```
[ERROR] Failed to execute goal org.jetbrains.dokka:dokka-maven-plugin:0.9.17:dokka (default) on project config: Execution default of goal org.jetbrains.dokka:dokka-maven-plugin:0.9.17:dokka failed: Guice provision errors:
[ERROR] 
[ERROR] 1) Error injecting constructor, java.lang.RuntimeException: Exception while loading package-list from ExternalDocumentationLinkImpl(url=http://docs.oracle.com/javase/11/docs/api/, packageListUrl=http://docs.oracle.com/javase/11/docs/api/package-list)
[ERROR]   at org.jetbrains.dokka.ExternalDocumentationLinkResolver.<init>(ExternalDocumentationLinkResolver.kt:28)
[ERROR]   at org.jetbrains.dokka.ExternalDocumentationLinkResolver.class(ExternalDocumentationLinkResolver.kt:28)
[ERROR]   while locating org.jetbrains.dokka.ExternalDocumentationLinkResolver
[ERROR]     for parameter 4 at org.jetbrains.dokka.DeclarationLinkResolver.<init>(DeclarationLinkResolver.kt:13)
[ERROR]   while locating org.jetbrains.dokka.DeclarationLinkResolver
[ERROR]     for parameter 0 at org.jetbrains.dokka.PackageDocs.<init>(PackageDocs.kt:13)
[ERROR]   at org.jetbrains.dokka.PackageDocs.class(PackageDocs.kt:12)
[ERROR]   while locating org.jetbrains.dokka.PackageDocs
```

**Comment by kamildoleglo** [comment]
Fixed in `1.4.10.2`
