### ISSUE TITLE
Maven plugin fails when network is unavailable

### ISSUE THREAD

**Issue by stlhrt** [Kotlin/dokka#470]
While working on https://github.com/powerflows/powerflows-dmn offline on the airport I faced an issue with **dokka** maven plugin.

When there is no network connection or DNS doesn't resolve docs.oracle.com build fails miserably...

```
[ERROR] Failed to execute goal org.jetbrains.dokka:dokka-maven-plugin:0.9.18:javadocJar (default) on project dmn-kotlin-dsl: Execution default of goal org.jetbrains.dokka:dokka-maven-plugin:0.9.18:javadocJar failed: Guice provision errors:
[ERROR] 
[ERROR] 1) Error injecting constructor, java.lang.RuntimeException: Exception while loading package-list from ExternalDocumentationLinkImpl(url=https://docs.oracle.com/javase/8/docs/api/, packageListUrl=https://docs.oracle.com/javase/8/docs/api/package-list)
[ERROR]   at org.jetbrains.dokka.ExternalDocumentationLinkResolver.<init>(ExternalDocumentationLinkResolver.kt:32)
[ERROR]   at org.jetbrains.dokka.ExternalDocumentationLinkResolver.class(ExternalDocumentationLinkResolver.kt:32)
[ERROR]   while locating org.jetbrains.dokka.ExternalDocumentationLinkResolver
[ERROR]     for parameter 4 at org.jetbrains.dokka.DeclarationLinkResolver.<init>(DeclarationLinkResolver.kt:10)
[ERROR]   while locating org.jetbrains.dokka.DeclarationLinkResolver
[ERROR]     for parameter 0 at org.jetbrains.dokka.PackageDocs.<init>(PackageDocs.kt:20)
[ERROR]   at org.jetbrains.dokka.PackageDocs.class(PackageDocs.kt:19)
[ERROR]   while locating org.jetbrains.dokka.PackageDocs
[ERROR] 
[ERROR] 1 error: Unknown host docs.oracle.com
```

Env:
```
java -version
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)
```
```
mvn -version
Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T20:33:14+02:00)
Maven home: /home/steel/.sdkman/candidates/maven/current
Java version: 1.8.0_201, vendor: Oracle Corporation, runtime: /home/steel/.sdkman/candidates/java/8.0.201-oracle/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.18.0-17-generic", arch: "amd64", family: "unix"
```
```xml
           <plugin>
                <groupId>org.jetbrains.dokka</groupId>
                <artifactId>dokka-maven-plugin</artifactId>
                <version>${dokka.version}</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>javadocJar</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <jdkVersion>8</jdkVersion>
                    <outputFormat>javadoc</outputFormat>
                    <reportNotDocumented>false</reportNotDocumented>
                    <noJdkLink>false</noJdkLink>
                </configuration>
            </plugin>
```

**Comment by semoro** [comment]
You should pass `<noJdkLink>true</noJdkLink>` and `<noStdlibLink>true</noStdlibLink>` to disable Dokka external links which requires internet connetion, or enable local caching of package-lists via `<cacheRoot>default</cacheRoot>`
