### ISSUE TITLE
Unable to download https://developer.android.com/reference/package-list

### ISSUE THREAD

**Issue by a-pikachu** [Kotlin/dokka#599]
**Describe the bug**
Exception while loading package-list from ExternalDocumentationLinkImpl(url=https://developer.android.com/reference/, packageListUrl=https://developer.android.com/reference/package-list)

**Expected behaviour**
Successfully load the package-list

**Dokka configuration**
0.9.18 org.jetbrains.dokka-android

```groovy
dokka { 
    outputFormat = 'html'
    ...
}
```

**Installation**
- Operating system: macOS
- Build tool: Gradle v5.4.1
- Dokka version: 0.9.18

**Additional context**
Add any other context about the problem here

**Comment by Armaxis** [comment]
It started failing for us today as well, around 12pm PST. We haven't changed anything either in Dokka configure or in server settings.
As a workaround this works:
**Dokka 0.9.18:**
```
dokka {
  ...
  noAndroidSdkLink = true
}
```
**Dokka 0.10.x:**
```
dokka {
    ...
    configuration {
        externalDocumentationLink {
            noAndroidSdkLink = true
        }
    }
}
```

**Comment by Armaxis** [comment]
`wget` shows a several weird redirects, but package-list is still accessible, and it looks like less than 20 redirects:

```
wget "https://developer.android.com/reference/package-list"
--2020-01-27 13:33:41--  https://developer.android.com/reference/package-list
Resolving developer.android.com (developer.android.com)... 172.217.164.110
Connecting to developer.android.com (developer.android.com)|172.217.164.110|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://developer.android.com/oauth2authorize?return_url=%2Freference%2Fpackage-list&prompt=none&auto_signin=True [following]
--2020-01-27 13:33:42--  https://developer.android.com/oauth2authorize?return_url=%2Freference%2Fpackage-list&prompt=none&auto_signin=True
Reusing existing connection to developer.android.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://accounts.google.com/o/oauth2/v2/auth?prompt=none&auto_signin=True&access_type=online&state=%7B%22csrf_token%22%3A+%22efdbd7794a5d631808215c2f764a5cdc3380134bf01efc5b18d72ee653e20efe%22%2C+%22return_url%22%3A+%22%2Freference%2Fpackage-list%22%7D&redirect_uri=https%3A%2F%2Fdeveloper.android.com%2Foauth2callback&response_type=code&client_id=721724668570-nbkv1cfusk7kk4eni4pjvepaus73b13t.apps.googleusercontent.com&scope=openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fgoogledevelopers+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile [following]
--2020-01-27 13:33:42--  https://accounts.google.com/o/oauth2/v2/auth?prompt=none&auto_signin=True&access_type=online&state=%7B%22csrf_token%22%3A+%22efdbd7794a5d631808215c2f764a5cdc3380134bf01efc5b18d72ee653e20efe%22%2C+%22return_url%22%3A+%22%2Freference%2Fpackage-list%22%7D&redirect_uri=https%3A%2F%2Fdeveloper.android.com%2Foauth2callback&response_type=code&client_id=721724668570-nbkv1cfusk7kk4eni4pjvepaus73b13t.apps.googleusercontent.com&scope=openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fgoogledevelopers+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile
Resolving accounts.google.com (accounts.google.com)... 216.58.195.77
Connecting to accounts.google.com (accounts.google.com)|216.58.195.77|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://developer.android.com/oauth2callback?state=%7B%22csrf_token%22:+%22efdbd7794a5d631808215c2f764a5cdc3380134bf01efc5b18d72ee653e20efe%22,+%22return_url%22:+%22/reference/package-list%22%7D&error_subtype=access_denied&error=interaction_required [following]
--2020-01-27 13:33:42--  https://developer.android.com/oauth2callback?state=%7B%22csrf_token%22:+%22efdbd7794a5d631808215c2f764a5cdc3380134bf01efc5b18d72ee653e20efe%22,+%22return_url%22:+%22/reference/package-list%22%7D&error_subtype=access_denied&error=interaction_required
Connecting to developer.android.com (developer.android.com)|172.217.164.110|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://developer.android.com/reference/package-list [following]
--2020-01-27 13:33:42--  https://developer.android.com/reference/package-list
Reusing existing connection to developer.android.com:443.
HTTP request sent, awaiting response... 200 OK
Length: 4087 (4.0K) [None]
Saving to: 'package-list'
package-list                          100%[========================================================================>]   3.99K  --.-KB/s    in 0s      
2020-01-27 13:33:42 (10.9 MB/s) - 'package-list' saved [4087/4087]
```

Dokka's crash stacktrace:

```
Caused by: java.lang.RuntimeException: Exception while loading package-list from ExternalDocumentationLinkImpl(url=https://developer.android.com/reference/, packageListUrl=https://developer.android.com/reference/package-list)
        at org.jetbrains.dokka.ExternalDocumentationLinkResolver.<init>(ExternalDocumentationLinkResolver.kt:164)
        at org.jetbrains.dokka.ExternalDocumentationLinkResolver$$FastClassByGuice$$34356095.newInstance(<generated>)
        at com.google.inject.internal.cglib.reflect.$FastConstructor.newInstance(FastConstructor.java:40)
        at com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:60)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1031)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.Scopes$1$1.get(Scopes.java:65)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:84)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:84)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1031)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.Scopes$1$1.get(Scopes.java:65)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
        at com.google.inject.internal.InjectorImpl$4$1.call(InjectorImpl.java:978)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1024)
        at com.google.inject.internal.InjectorImpl$4.get(InjectorImpl.java:974)
        ... 100 more
Caused by: java.net.ProtocolException: Server redirected too many  times (20)
        at org.jetbrains.dokka.ExternalDocumentationLinkResolver.doOpenConnectionToReadContent(ExternalDocumentationLinkResolver.kt:56)
        at org.jetbrains.dokka.ExternalDocumentationLinkResolver.doOpenConnectionToReadContent$default(ExternalDocumentationLinkResolver.kt:49)
        at org.jetbrains.dokka.ExternalDocumentationLinkResolver.loadPackageList(ExternalDocumentationLinkResolver.kt:118)
        at org.jetbrains.dokka.ExternalDocumentationLinkResolver.<init>(ExternalDocumentationLinkResolver.kt:162)
        ... 126 more
```

Overall, this is different issue from #213 - seems like something change about the way  https://developer.android.com/reference/package-list itself is hosted.

**Comment by inez** [comment]
We (Square) are experience the same issue since this morning. It really looks like hosting of https://developer.android.com/reference/package-list changes, and maybe it has to do with problems Google had earlier today (multiple services were down).

**Comment by inez** [comment]
Ok, so I understand the problem now, if you run `wget --no-cookies https://developer.android.com/reference/package-list` (so wget with following redirects but without accepting cookies - which is what dokka is doing) you also get `20 redirections exceeded.`

```
wget --no-cookies https://developer.android.com/reference/package-list
--2020-01-27 17:37:18--  https://developer.android.com/reference/package-list
Resolving developer.android.com (developer.android.com)... 172.217.164.110
Connecting to developer.android.com (developer.android.com)|172.217.164.110|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://developer.android.com/oauth2authorize?return_url=%2Freference%2Fpackage-list&prompt=none&auto_signin=True [following]
--2020-01-27 17:37:18--  https://developer.android.com/oauth2authorize?return_url=%2Freference%2Fpackage-list&prompt=none&auto_signin=True
Reusing existing connection to developer.android.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://accounts.google.com/o/oauth2/v2/auth?prompt=none&auto_signin=True&access_type=online&state=%7B%22csrf_token%22%3A+%229eb3c6bac72a04e094b9c1b7387c4a62e3d2128ffd8660bfa1c9352398574f69%22%2C+%22return_url%22%3A+%22%2Freference%2Fpackage-list%22%7D&redirect_uri=https%3A%2F%2Fdeveloper.android.com%2Foauth2callback&response_type=code&client_id=721724668570-nbkv1cfusk7kk4eni4pjvepaus73b13t.apps.googleusercontent.com&scope=openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fgoogledevelopers+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile [following]
--2020-01-27 17:37:18--  https://accounts.google.com/o/oauth2/v2/auth?prompt=none&auto_signin=True&access_type=online&state=%7B%22csrf_token%22%3A+%229eb3c6bac72a04e094b9c1b7387c4a62e3d2128ffd8660bfa1c9352398574f69%22%2C+%22return_url%22%3A+%22%2Freference%2Fpackage-list%22%7D&redirect_uri=https%3A%2F%2Fdeveloper.android.com%2Foauth2callback&response_type=code&client_id=721724668570-nbkv1cfusk7kk4eni4pjvepaus73b13t.apps.googleusercontent.com&scope=openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fgoogledevelopers+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile
Resolving accounts.google.com (accounts.google.com)... 216.58.195.77
Connecting to accounts.google.com (accounts.google.com)|216.58.195.77|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://developer.android.com/oauth2callback?state=%7B%22csrf_token%22:+%229eb3c6bac72a04e094b9c1b7387c4a62e3d2128ffd8660bfa1c9352398574f69%22,+%22return_url%22:+%22/reference/package-list%22%7D&error_subtype=access_denied&error=interaction_required [following]
--2020-01-27 17:37:18--  https://developer.android.com/oauth2callback?state=%7B%22csrf_token%22:+%229eb3c6bac72a04e094b9c1b7387c4a62e3d2128ffd8660bfa1c9352398574f69%22,+%22return_url%22:+%22/reference/package-list%22%7D&error_subtype=access_denied&error=interaction_required
Connecting to developer.android.com (developer.android.com)|172.217.164.110|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://developer.android.com/reference/package-list [following]
--2020-01-27 17:37:18--  https://developer.android.com/reference/package-list
Reusing existing connection to developer.android.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://developer.android.com/oauth2authorize?return_url=%2Freference%2Fpackage-list&prompt=none&auto_signin=True [following]
--2020-01-27 17:37:18--  https://developer.android.com/oauth2authorize?return_url=%2Freference%2Fpackage-list&prompt=none&auto_signin=True
Reusing existing connection to developer.android.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://accounts.google.com/o/oauth2/v2/auth?prompt=none&auto_signin=True&access_type=online&state=%7B%22csrf_token%22%3A+%220167eaf4c5d02bd7c98ac961136762da19adb20ac0fd9129436a5459c7203444%22%2C+%22return_url%22%3A+%22%2Freference%2Fpackage-list%22%7D&redirect_uri=https%3A%2F%2Fdeveloper.android.com%2Foauth2callback&response_type=code&client_id=721724668570-nbkv1cfusk7kk4eni4pjvepaus73b13t.apps.googleusercontent.com&scope=openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fgoogledevelopers+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile [following]
--2020-01-27 17:37:18--  https://accounts.google.com/o/oauth2/v2/auth?prompt=none&auto_signin=True&access_type=online&state=%7B%22csrf_token%22%3A+%220167eaf4c5d02bd7c98ac961136762da19adb20ac0fd9129436a5459c7203444%22%2C+%22return_url%22%3A+%22%2Freference%2Fpackage-list%22%7D&redirect_uri=https%3A%2F%2Fdeveloper.android.com%2Foauth2callback&response_type=code&client_id=721724668570-nbkv1cfusk7kk4eni4pjvepaus73b13t.apps.googleusercontent.com&scope=openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fgoogledevelopers+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile
Connecting to accounts.google.com (accounts.google.com)|216.58.195.77|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://developer.android.com/oauth2callback?state=%7B%22csrf_token%22:+%220167eaf4c5d02bd7c98ac961136762da19adb20ac0fd9129436a5459c7203444%22,+%22return_url%22:+%22/reference/package-list%22%7D&error_subtype=access_denied&error=interaction_required [following]
--2020-01-27 17:37:18--  https://developer.android.com/oauth2callback?state=%7B%22csrf_token%22:+%220167eaf4c5d02bd7c98ac961136762da19adb20ac0fd9129436a5459c7203444%22,+%22return_url%22:+%22/reference/package-list%22%7D&error_subtype=access_denied&error=interaction_required
Connecting to developer.android.com (developer.android.com)|172.217.164.110|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://developer.android.com/reference/package-list [following]
--2020-01-27 17:37:19--  https://developer.android.com/reference/package-list
Reusing existing connection to developer.android.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://developer.android.com/oauth2authorize?return_url=%2Freference%2Fpackage-list&prompt=none&auto_signin=True [following]
--2020-01-27 17:37:19--  https://developer.android.com/oauth2authorize?return_url=%2Freference%2Fpackage-list&prompt=none&auto_signin=True
Reusing existing connection to developer.android.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://accounts.google.com/o/oauth2/v2/auth?prompt=none&auto_signin=True&access_type=online&state=%7B%22csrf_token%22%3A+%22f2b7a11dfce972e4b81683f2efd6ebed595127b0183444119deeec6c3f80f6f8%22%2C+%22return_url%22%3A+%22%2Freference%2Fpackage-list%22%7D&redirect_uri=https%3A%2F%2Fdeveloper.android.com%2Foauth2callback&response_type=code&client_id=721724668570-nbkv1cfusk7kk4eni4pjvepaus73b13t.apps.googleusercontent.com&scope=openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fgoogledevelopers+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile [following]
--2020-01-27 17:37:19--  https://accounts.google.com/o/oauth2/v2/auth?prompt=none&auto_signin=True&access_type=online&state=%7B%22csrf_token%22%3A+%22f2b7a11dfce972e4b81683f2efd6ebed595127b0183444119deeec6c3f80f6f8%22%2C+%22return_url%22%3A+%22%2Freference%2Fpackage-list%22%7D&redirect_uri=https%3A%2F%2Fdeveloper.android.com%2Foauth2callback&response_type=code&client_id=721724668570-nbkv1cfusk7kk4eni4pjvepaus73b13t.apps.googleusercontent.com&scope=openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fgoogledevelopers+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile
Connecting to accounts.google.com (accounts.google.com)|216.58.195.77|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://developer.android.com/oauth2callback?state=%7B%22csrf_token%22:+%22f2b7a11dfce972e4b81683f2efd6ebed595127b0183444119deeec6c3f80f6f8%22,+%22return_url%22:+%22/reference/package-list%22%7D&error_subtype=access_denied&error=interaction_required [following]
--2020-01-27 17:37:19--  https://developer.android.com/oauth2callback?state=%7B%22csrf_token%22:+%22f2b7a11dfce972e4b81683f2efd6ebed595127b0183444119deeec6c3f80f6f8%22,+%22return_url%22:+%22/reference/package-list%22%7D&error_subtype=access_denied&error=interaction_required
Connecting to developer.android.com (developer.android.com)|172.217.164.110|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://developer.android.com/reference/package-list [following]
--2020-01-27 17:37:19--  https://developer.android.com/reference/package-list
Reusing existing connection to developer.android.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://developer.android.com/oauth2authorize?return_url=%2Freference%2Fpackage-list&prompt=none&auto_signin=True [following]
--2020-01-27 17:37:19--  https://developer.android.com/oauth2authorize?return_url=%2Freference%2Fpackage-list&prompt=none&auto_signin=True
Reusing existing connection to developer.android.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://accounts.google.com/o/oauth2/v2/auth?prompt=none&auto_signin=True&access_type=online&state=%7B%22csrf_token%22%3A+%223c639f1aa3dd4209242efac71c2c539ccc2e92d79e8b19297bde1ac788d230f7%22%2C+%22return_url%22%3A+%22%2Freference%2Fpackage-list%22%7D&redirect_uri=https%3A%2F%2Fdeveloper.android.com%2Foauth2callback&response_type=code&client_id=721724668570-nbkv1cfusk7kk4eni4pjvepaus73b13t.apps.googleusercontent.com&scope=openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fgoogledevelopers+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile [following]
--2020-01-27 17:37:19--  https://accounts.google.com/o/oauth2/v2/auth?prompt=none&auto_signin=True&access_type=online&state=%7B%22csrf_token%22%3A+%223c639f1aa3dd4209242efac71c2c539ccc2e92d79e8b19297bde1ac788d230f7%22%2C+%22return_url%22%3A+%22%2Freference%2Fpackage-list%22%7D&redirect_uri=https%3A%2F%2Fdeveloper.android.com%2Foauth2callback&response_type=code&client_id=721724668570-nbkv1cfusk7kk4eni4pjvepaus73b13t.apps.googleusercontent.com&scope=openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fgoogledevelopers+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile
Connecting to accounts.google.com (accounts.google.com)|216.58.195.77|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://developer.android.com/oauth2callback?state=%7B%22csrf_token%22:+%223c639f1aa3dd4209242efac71c2c539ccc2e92d79e8b19297bde1ac788d230f7%22,+%22return_url%22:+%22/reference/package-list%22%7D&error_subtype=access_denied&error=interaction_required [following]
--2020-01-27 17:37:19--  https://developer.android.com/oauth2callback?state=%7B%22csrf_token%22:+%223c639f1aa3dd4209242efac71c2c539ccc2e92d79e8b19297bde1ac788d230f7%22,+%22return_url%22:+%22/reference/package-list%22%7D&error_subtype=access_denied&error=interaction_required
Connecting to developer.android.com (developer.android.com)|172.217.164.110|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://developer.android.com/reference/package-list [following]
--2020-01-27 17:37:19--  https://developer.android.com/reference/package-list
Reusing existing connection to developer.android.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://developer.android.com/oauth2authorize?return_url=%2Freference%2Fpackage-list&prompt=none&auto_signin=True [following]
--2020-01-27 17:37:19--  https://developer.android.com/oauth2authorize?return_url=%2Freference%2Fpackage-list&prompt=none&auto_signin=True
Reusing existing connection to developer.android.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://accounts.google.com/o/oauth2/v2/auth?prompt=none&auto_signin=True&access_type=online&state=%7B%22csrf_token%22%3A+%2255ca8cf2f1750a09100029f5b4aaca99d824c535ecfd1f5099a9e057fa2555fa%22%2C+%22return_url%22%3A+%22%2Freference%2Fpackage-list%22%7D&redirect_uri=https%3A%2F%2Fdeveloper.android.com%2Foauth2callback&response_type=code&client_id=721724668570-nbkv1cfusk7kk4eni4pjvepaus73b13t.apps.googleusercontent.com&scope=openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fgoogledevelopers+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile [following]
--2020-01-27 17:37:19--  https://accounts.google.com/o/oauth2/v2/auth?prompt=none&auto_signin=True&access_type=online&state=%7B%22csrf_token%22%3A+%2255ca8cf2f1750a09100029f5b4aaca99d824c535ecfd1f5099a9e057fa2555fa%22%2C+%22return_url%22%3A+%22%2Freference%2Fpackage-list%22%7D&redirect_uri=https%3A%2F%2Fdeveloper.android.com%2Foauth2callback&response_type=code&client_id=721724668570-nbkv1cfusk7kk4eni4pjvepaus73b13t.apps.googleusercontent.com&scope=openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fgoogledevelopers+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile
Connecting to accounts.google.com (accounts.google.com)|216.58.195.77|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://developer.android.com/oauth2callback?state=%7B%22csrf_token%22:+%2255ca8cf2f1750a09100029f5b4aaca99d824c535ecfd1f5099a9e057fa2555fa%22,+%22return_url%22:+%22/reference/package-list%22%7D&error_subtype=access_denied&error=interaction_required [following]
--2020-01-27 17:37:20--  https://developer.android.com/oauth2callback?state=%7B%22csrf_token%22:+%2255ca8cf2f1750a09100029f5b4aaca99d824c535ecfd1f5099a9e057fa2555fa%22,+%22return_url%22:+%22/reference/package-list%22%7D&error_subtype=access_denied&error=interaction_required
Connecting to developer.android.com (developer.android.com)|172.217.164.110|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://developer.android.com/reference/package-list [following]
--2020-01-27 17:37:20--  https://developer.android.com/reference/package-list
Reusing existing connection to developer.android.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://developer.android.com/oauth2authorize?return_url=%2Freference%2Fpackage-list&prompt=none&auto_signin=True [following]
20 redirections exceeded.
```

**Comment by Armaxis** [comment]
Folks at Google fixed the issue. It should work now! I think this ticket can be closed now 😃

**Comment by a-pikachu** [comment]
My build is working again now

**Comment by stephanenicolas** [comment]
It would be interesting to see if Google could provide a better solution as outages seem to happen still. Maybe this file could be versioned so that it can be mirrored internally in our CI infrastructure easily.

**Comment by AristotelispetrosBobas-TomTom** [comment]
We are having the same issues with the package list, increasing our build time tremendously: 

_Failed to download package-list from https://developer.android.com/reference/kotlin/package-list, this might suggest that remote resource is not available, module is empty or dokka output got corrupted_
