### ISSUE TITLE
How to provide path for tools.jar

### ISSUE THREAD

**Issue by rahullohra2903** [Kotlin/dokka#816]
**Question**
How to provide tools.jar. Please provide an example
I am trying below way but I am getting exception

```
 java -cp "/home/rahulkumarlohra-xps/Apps/lib/jdk1.8.0_221/lib/tools.jar" -jar dokka.jar -pass -src ./src/ -format javadoc -output ./docs
Exception in thread "main" java.lang.Exception: tools.jar not found, please check it, also you can provide it manually, using -cp
	at org.jetbrains.dokka.MainKt.findToolsJar(main.kt:201)
	at org.jetbrains.dokka.MainKt.createClassLoaderWithTools(main.kt:207)
	at org.jetbrains.dokka.MainKt.startWithToolsJar(main.kt:219)
	at org.jetbrains.dokka.MainKt.main(main.kt:271)

````

**Installation**
- Operating system: Linux
- Dokka version: 0.10.1

**Comment by kamildoleglo** [comment]
Fixed in 1.4.10.2
