### ISSUE TITLE
[CLI] 0.10.1 jar errors on parsing source directory as arguments

### ISSUE THREAD

**Issue by buildbreaker** [Kotlin/dokka#942]
**Describe the bug**
I'm trying to generate javadocs using dokka's CLI tool. I'm having issues with the latest release jar and I'm getting an error.

I've used dokka before and it looks like 0.9.18 was the last release which does generate javadocs.

The command I used:
`java -jar dokka0.jar ./ -format javadoc -output ./`

The output:
```
Exception in thread "main" kotlinx.cli.CommandLineException: Unexpected positional argument: './'
	at kotlinx.cli.CommandLineParser.handlePositionalArgument(CommandLineParser.kt:81)
	at kotlinx.cli.CommandLineParser.doParse(CommandLineParser.kt:53)
	at kotlinx.cli.CommandLineParser.parseTokenized(CommandLineParser.kt:21)
	at kotlinx.cli.CommandLineParser.parse(CommandLineParser.kt:11)
	at kotlinx.cli.CommandLineParser.parse(CommandLineParser.kt:7)
	at kotlinx.cli.ParseKt.parseArgs(parse.kt:4)
	at org.jetbrains.dokka.ParseContext.parse(DokkaArgumentsParser.kt:54)
	at org.jetbrains.dokka.DokkaArgumentsParser.parseInto(DokkaArgumentsParser.kt:118)
	at org.jetbrains.dokka.MainKt.createConfiguration(main.kt:261)
	at org.jetbrains.dokka.MainKt.main(main.kt:269)
```

**Expected behaviour**
Javadocs are generated without errors

**Screenshots**
Created a demo with github actions here: https://github.com/buildbreaker/HelloWorld/pull/3
`Dokka CLI error demo / dokka_0_10_1` actions job fails

**To Reproduce**
Commands which I've used:
https://github.com/buildbreaker/HelloWorld/pull/3/files#diff-66045cc17accee351647865b5a9816dcR31-R39
```
          curl https://github.com/Kotlin/dokka/releases/download/0.10.1/dokka-fatjar-0.10.1.jar --output dokka0.10.1.jar -L
          shasum -a 256 dokka0.10.1.jar
          mkdir tmp
          output_directory=tmp
          java -jar dokka0.10.1.jar ./ -format javadoc -output $output_directory
          echo "~~~~~~~~~~~"
          echo "Result:"
          ls $output_directory
          echo "~~~~~~~~~~~"
```

**Dokka configuration**
N/a

**Installation**
- Operating system: macOS/Linux
- Build tool: CLI
- Dokka version: 0.10.1

**Additional context**
Github actions demo in this PR:
https://github.com/buildbreaker/HelloWorld/pull/3

Thank you!

**Comment by buildbreaker** [comment]
I'm going to close my PR but the failed jobs and logs should still be available

**Comment by kamildoleglo** [comment]
The CLI configuration has changed since 0.9.18 quite extensively, please refer to the migration guide in the [FAQ](https://github.com/Kotlin/dokka/wiki/faq)
