### ISSUE TITLE
fatJar 0.10.1 or 0.10.0 CRASHES when used from the command line

### ISSUE THREAD

**Issue by lesv** [Kotlin/dokka#966]
**Describe the bug**
Executing the FatJar from the command line doesn't appear to work anymore.

**Expected behaviour**
Not crash

**Screenshots**
```bash
java -jar ../../dokka-fatjar-0.10.1.jar -h
Usage: dokka [-h] [-output] [-format] [-generateIndexPages] [-cacheRoot] [-pass] [-globalPackageOptions] [-globalLinks] [-globalSrcLink]

  -h, --help                Prints help
  -output                   Output directory path
  -format                   Output format (text, html, markdown, jekyll, kotlin-website)
  -generateIndexPages       Generate index page
  -cacheRoot                Path to cache folder, or 'default' to use ~/.cache/dokka, if not provided caching is disabled
  -pass                     Single dokka pass
  -globalPackageOptions     List of package passConfiguration in format "prefix,-deprecated,-privateApi,+warnUndocumented,+suppress;..."
  -globalLinks              External documentation links in format url^packageListUrl^^url2...
  -globalSrcLink            Mapping between a source directory and a Web site for browsing the code
Exception in thread "main" kotlinx.cli.HelpPrintedException
	at kotlinx.cli.FlagArgumentsKt$help$1.invoke(FlagArguments.kt:100)
	at kotlinx.cli.FlagAction$DefaultImpls.invoke(Actions.kt:9)
	at kotlinx.cli.FlagActionBase.invoke(FlagArguments.kt:4)
	at kotlinx.cli.CommandLineParser.doParse(CommandLineParser.kt:56)
	at kotlinx.cli.CommandLineParser.parseTokenized(CommandLineParser.kt:21)
	at kotlinx.cli.CommandLineParser.parse(CommandLineParser.kt:11)
	at kotlinx.cli.CommandLineParser.parse(CommandLineParser.kt:7)
	at kotlinx.cli.ParseKt.parseArgs(parse.kt:4)
	at org.jetbrains.dokka.ParseContext.parse(DokkaArgumentsParser.kt:54)
	at org.jetbrains.dokka.DokkaArgumentsParser.parseInto(DokkaArgumentsParser.kt:118)
	at org.jetbrains.dokka.MainKt.createConfiguration(main.kt:261)
	at org.jetbrains.dokka.MainKt.main(main.kt:269)
```
or
```
java -jar ~/Downloads/dokka-fatjar-0.10.0.jar -h
Usage: dokka [-h] [-output] [-format] [-generateIndexPages] [-cacheRoot] [-pass] [-globalPackageOptions] [-globalLinks] [-globalSrcLink]

  -h, --help                Prints help
  -output                   Output directory path
  -format                   Output format (text, html, markdown, jekyll, kotlin-website)
  -generateIndexPages       Generate index page
  -cacheRoot                Path to cache folder, or 'default' to use ~/.cache/dokka, if not provided caching is disabled
  -pass                     Single dokka pass
  -globalPackageOptions     List of package passConfiguration in format "prefix,-deprecated,-privateApi,+warnUndocumented,+suppress;..."
  -globalLinks              External documentation links in format url^packageListUrl^^url2...
  -globalSrcLink            Mapping between a source directory and a Web site for browsing the code
Exception in thread "main" kotlinx.cli.HelpPrintedException
	at kotlinx.cli.FlagArgumentsKt$help$1.invoke(FlagArguments.kt:100)
	at kotlinx.cli.FlagAction$DefaultImpls.invoke(Actions.kt:9)
	at kotlinx.cli.FlagActionBase.invoke(FlagArguments.kt:4)
	at kotlinx.cli.CommandLineParser.doParse(CommandLineParser.kt:56)
	at kotlinx.cli.CommandLineParser.parseTokenized(CommandLineParser.kt:21)
	at kotlinx.cli.CommandLineParser.parse(CommandLineParser.kt:11)
	at kotlinx.cli.CommandLineParser.parse(CommandLineParser.kt:7)
	at kotlinx.cli.ParseKt.parseArgs(parse.kt:4)
	at org.jetbrains.dokka.ParseContext.parse(DokkaArgumentsParser.kt:54)
	at org.jetbrains.dokka.DokkaArgumentsParser.parseInto(DokkaArgumentsParser.kt:118)
	at org.jetbrains.dokka.MainKt.createConfiguration(main.kt:260)
	at org.jetbrains.dokka.MainKt.main(main.kt:266)
```
I am able to use 0.9.xx successfully.

**Installation**
- Operating system: macOS/Windows/Linux
- Build tool: bash
- Dokka version: 0.10.1
openjdk version "11.0.7" 2020-04-14 LTS
OpenJDK Runtime Environment Zulu11.39+15-CA (build 11.0.7+10-LTS)
OpenJDK 64-Bit Server VM Zulu11.39+15-CA (build 11.0.7+10-LTS, mixed mode)

I get the same results with:
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (Zulu 8.46.0.19-CA-macosx) (build 1.8.0_252-b14)
OpenJDK 64-Bit Server VM (Zulu 8.46.0.19-CA-macosx) (build 25.252-b14, mixed mode)

**Comment by kamildoleglo** [comment]
This was a known bug in kotlinx.cli, fixed in the updated version that we migrated to in 0.11.0. 

Fortunately this exception is meaningless, you can still use dokka, printing help will just throw an exception
